#!/usr/bin/env python3
"""Emit assets/scene_lost_child.xml — a crowded indoor concourse.

GENERATED from ``scripts/plaza_layout.py`` and ``scripts/lost_cast.py`` rather
than hand-written, so the obstacles the route planner inflates, the surfaces the
clearance gate measures and the bodies the camera ray-casts against are all the
same objects.  A scene edit that moves the kiosk moves it everywhere at once.

Everything except the robot is ``contype="0" conaffinity="0"``: kinematic
scenery that cannot touch or push the robot.  The adults are mocap bodies posed
analytically each tick, so they add no degrees of freedom to the floating base
and the walking policy sees exactly the robot it was trained on.  A step the
duck takes can therefore never be the result of somebody nudging it.

THE OCCLUDERS BEING NON-COLLIDING IS DELIBERATE.  If they collided, "the rejoin
route went round the kiosk" would be enforced by the contact solver rather than
demonstrated by the planner, and a duck that scraped along the kiosk for five
seconds would still pass.  With non-colliding scenery, avoiding it is a property
of the CONTROLLER, graded by measured surface clearance every control tick.

PERSON GEOMETRY IS SCALED BY STATURE, and that is what makes the height feature
real: ``sofia`` is not labelled shorter, she IS shorter, her head sphere sits
lower, and the camera's topmost sample of her is genuinely nearer the ground.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from lost_cast import BASE_ORIGIN_Z, PEOPLE  # noqa: E402
from lost_geometry import DUCK_START_XY, DUCK_START_YAW_DEG  # noqa: E402
from plaza_layout import (  # noqa: E402
    FLOOR_HALF,
    OBSTACLES,
    WALL_HALF_Z,
    WALL_T,
)

HEADER = """<mujoco model="scene_lost_child">
    <!-- lost-child-find-person: a crowded indoor concourse.
         GENERATED by tools/build_scene.py - edit that script, not this file.

         Every wall, kiosk, column, crate, panel and person is contype="0"
         conaffinity="0": kinematic scenery that cannot touch or push the robot.
         Going round an occluder is therefore a property of the CONTROLLER,
         graded by measured surface clearance, not by the contact solver.

         The occluders are all at least 0.90 m tall, which is above the highest
         point the head camera samples on a person (z = 0.66), so each one
         removes EVERY sample of anybody behind it.  The bench is 0.24 m: a real
         route obstacle that is deliberately not an occluder. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.74 0.74 0.74" ambient="0.44 0.44 0.44" specular="0 0 0" />
        <rgba haze="0.18 0.20 0.24 1" />
        <global azimuth="140" elevation="-28" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.17 0.19 0.25" rgb2="0.04 0.05 0.07"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.28 0.28 0.31" rgb2="0.23 0.23 0.26" markrgb="0.38 0.38 0.42"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="18 18" reflectance="0.05" />
        <material name="hallmat" rgba="0.47 0.46 0.44 1" />
        <material name="wallmat" rgba="0.69 0.68 0.65 1" />
        <material name="kioskmat" rgba="0.30 0.38 0.50 1" />
        <material name="kiosktop" rgba="0.86 0.84 0.78 1" />
        <material name="columnmat" rgba="0.72 0.71 0.68 1" />
        <material name="cratemat" rgba="0.55 0.41 0.26 1" />
        <material name="panelmat" rgba="0.20 0.46 0.42 1" />
        <material name="benchmat" rgba="0.44 0.33 0.24 1" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.12 0.15 0.22 1" />
        <material name="shoemat" rgba="0.05 0.05 0.06 1" />
        <material name="capmat" rgba="0.10 0.12 0.16 1" />
        <material name="satchelmat" rgba="0.30 0.24 0.18 1" />
        <material name="lastseenmat" rgba="0.96 0.72 0.20 0.55" />
        <material name="trailmat" rgba="0.96 0.72 0.20 0.34" />
        <material name="routemat" rgba="0.28 0.72 0.98 0.42" />
        <material name="targetmat" rgba="0.20 0.92 0.46 0.50" />
        <material name="rejectmat" rgba="0.95 0.26 0.20 0.50" />
"""

WORLD_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.2" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="lost_rig" mocap="true" pos="0 0 0.20">
            <camera name="lost_camera" fovy="58" />
        </body>
"""

# How many world-space trail discs and route markers the scene carries.
TRAIL_DISCS = 14
ROUTE_DISCS = 8


def _box(name, pos, size, material, quat=None) -> str:
    extra = (f' quat="{quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f} {quat[3]:.6f}"'
             if quat else "")
    return (
        f'        <geom name="{name}" type="box" pos="{pos[0]:.4f} {pos[1]:.4f} '
        f'{pos[2]:.4f}" size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}"'
        f'{extra} material="{material}" contype="0" conaffinity="0" />\n'
    )


def _cylinder(name, pos, radius, half_h, material) -> str:
    return (
        f'        <geom name="{name}" type="cylinder" pos="{pos[0]:.4f} '
        f'{pos[1]:.4f} {pos[2]:.4f}" size="{radius:.4f} {half_h:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def _yaw_quat(yaw: float) -> tuple[float, float, float, float]:
    return (math.cos(0.5 * yaw), 0.0, 0.0, math.sin(0.5 * yaw))


def hall() -> str:
    """Concourse floor slab and the four perimeter walls."""
    parts = ["\n        <!-- concourse floor and perimeter walls -->\n"]
    parts.append(_box("hall_floor", (0.0, 0.0, 0.0015),
                      (FLOOR_HALF[0], FLOOR_HALF[1], 0.0015), "hallmat"))
    for tag, sign in (("e", +1.0), ("w", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (sign * (FLOOR_HALF[0] + WALL_T), 0.0, WALL_HALF_Z),
            (WALL_T, FLOOR_HALF[1] + 2 * WALL_T, WALL_HALF_Z), "wallmat"))
    for tag, sign in (("n", +1.0), ("s", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (0.0, sign * (FLOOR_HALF[1] + WALL_T), WALL_HALF_Z),
            (FLOOR_HALF[0] + 2 * WALL_T, WALL_T, WALL_HALF_Z), "wallmat"))
    return "".join(parts)


def furniture() -> str:
    """Every obstacle in :data:`plaza_layout.OBSTACLES`, at its declared height.

    Geom names are ``obs_<name>`` so ``rollout_lost.scenery_geom_names`` can
    collect them from the model rather than from a hand-kept list.
    """
    material = {"kiosk": "kioskmat", "column_w": "columnmat",
                "column_s": "columnmat", "crates": "cratemat",
                "panel_n": "panelmat", "bench": "benchmat"}
    parts = ["\n        <!-- occluders and route obstacles -->\n"]
    for obstacle in OBSTACLES:
        half_h = 0.5 * obstacle.height_m
        center = (obstacle.center[0], obstacle.center[1], half_h)
        if obstacle.kind == "circle":
            parts.append(_cylinder(f"obs_{obstacle.name}", center,
                                   obstacle.radius, half_h,
                                   material[obstacle.name]))
        else:
            parts.append(_box(f"obs_{obstacle.name}", center,
                              (obstacle.half[0], obstacle.half[1], half_h),
                              material[obstacle.name]))
    # A counter top on the kiosk, so it reads as a kiosk rather than a slab.
    kiosk = next(o for o in OBSTACLES if o.name == "kiosk")
    parts.append(_box("obs_kiosk_top",
                      (kiosk.center[0], kiosk.center[1], kiosk.height_m + 0.02),
                      (kiosk.half[0] + 0.04, kiosk.half[1] + 0.04, 0.022),
                      "kiosktop"))
    return "".join(parts)


def markers() -> str:
    """Mocap discs: last-known footprint, world trail, rejoin route, verdicts."""
    entries = [("last_seen_marker", "lastseenmat", 0.115, 0.011),
               ("target_marker", "targetmat", 0.100, 0.010)]
    entries += [(f"trail_{i}", "trailmat", 0.043, 0.006)
                for i in range(TRAIL_DISCS)]
    entries += [(f"route_{i}", "routemat", 0.055, 0.007)
                for i in range(ROUTE_DISCS)]
    entries += [(f"reject_marker_{i}", "rejectmat", 0.078, 0.008)
                for i in range(2)]
    parts = ["\n        <!-- decision markers: mocap discs, non-colliding -->\n"]
    for name, material, radius, half_h in entries:
        parts.append(
            f'        <body name="{name}" mocap="true" pos="0 0 -3.0">\n'
            f'            <geom name="{name}_disc" type="cylinder"'
            f' size="{radius:.3f} {half_h:.3f}" material="{material}"'
            f' contype="0" conaffinity="0" />\n'
            f"        </body>\n"
        )
    return "".join(parts)


def person_block(person) -> str:
    """One adult, SCALED BY STATURE so height is geometry, not a label."""
    s = person.stature
    name = person.name
    lines = [
        f'        <body name="person_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_torso" type="capsule"'
        f' fromto="0 0 {-0.10 * s:.4f} 0 0 {0.16 * s:.4f}"'
        f' size="{0.078 * s:.4f}" material="{name}_shirt"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere"'
        f' pos="0 0 {0.255 * s:.4f}" size="{0.064 * s:.4f}" material="skinmat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere"'
        f' pos="{0.060 * s:.4f} 0 {0.252 * s:.4f}" size="{0.019 * s:.4f}"'
        f' material="{name}_shirt" contype="0" conaffinity="0" />',
    ]
    if person.cap:
        lines.append(
            f'            <geom name="{name}_cap" type="cylinder"'
            f' pos="0 0 {0.312 * s:.4f}" size="{0.062 * s:.4f} {0.016 * s:.4f}"'
            f' material="capmat" contype="0" conaffinity="0" />')
        lines.append(
            f'            <geom name="{name}_brim" type="box"'
            f' pos="{0.058 * s:.4f} 0 {0.300 * s:.4f}"'
            f' size="{0.050 * s:.4f} {0.058 * s:.4f} {0.006 * s:.4f}"'
            f' material="capmat" contype="0" conaffinity="0" />')
    if person.satchel:
        lines.append(
            f'            <geom name="{name}_satchel" type="box"'
            f' pos="{-0.052 * s:.4f} {0.060 * s:.4f} {0.020 * s:.4f}"'
            f' size="{0.052 * s:.4f} {0.030 * s:.4f} {0.062 * s:.4f}"'
            f' material="satchelmat" contype="0" conaffinity="0" />')
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}"'
            f' pos="0 {sy * s:+.4f} {-0.10 * s:.4f}">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.26 * s:.4f}"'
            f' size="{0.033 * s:.4f}" material="trousermat"'
            f' contype="0" conaffinity="0" />'
            f'<geom type="capsule"'
            f' fromto="0 0 {-0.26 * s:.4f} {0.072 * s:.4f} 0 {-0.272 * s:.4f}"'
            f' size="{0.035 * s:.4f}" material="shoemat"'
            f' contype="0" conaffinity="0" /></body>')
    for side, sy in (("l", 0.078), ("r", -0.078)):
        lines.append(
            f'            <body name="{name}_arm_{side}"'
            f' pos="0 {sy * s:+.4f} {0.115 * s:.4f}">'
            f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.205 * s:.4f}"'
            f' size="{0.026 * s:.4f}" material="skinmat"'
            f' contype="0" conaffinity="0" /></body>')
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    materials = "".join(
        f'        <material name="{p.name}_shirt" rgba="{p.rgba}" />\n'
        for p in PEOPLE)
    parts = [HEADER + materials + WORLD_OPEN,
             hall(), furniture(), markers(),
             "\n        <!-- adults: mocap, non-colliding, scripted -->\n"]
    parts.extend(person_block(p) for p in PEOPLE)
    parts.append("    </worldbody>\n\n")

    quat = _yaw_quat(math.radians(DUCK_START_YAW_DEG))
    base = (f"{DUCK_START_XY[0]:.4f} {DUCK_START_XY[1]:.4f} 0.12 "
            f"{quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f} {quat[3]:.6f}")
    hinge_pad = " ".join(["0"] * (4 * len(PEOPLE)))
    stand = (
        f"        {base}\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 4 * len(PEOPLE)))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="{base} {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = (Path(__file__).resolve().parents[1] / "assets"
           / "scene_lost_child.xml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  people={len(PEOPLE)}  obstacles={len(OBSTACLES)}  "
          f"base_origin_z={BASE_ORIGIN_Z}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
