#!/usr/bin/env python3
"""Emit assets/scene_narrow_corridor.xml.

A NARROW INDOOR CORRIDOR, 0.54 m wide between the wall faces, with four side
recesses and a lobby at the far end.  The corridor is deliberately too tight for
the duck and an adult to pass side by side: ``corridor.corridor_passing_geometry``
evaluates that from the measured radii and a test pins it, so the scenario's
central premise is arithmetic rather than art direction.

The four bays, and why two of them are useless
----------------------------------------------
``bay_shallow``  a 0.12 m niche.  Too shallow: the duck's footprint cannot get
                 out of the centre passage inside it, whatever it does.
``bay_crates``   a full-depth recess with a stack of crates parked in it.  The
                 crates begin at |y| = 0.40, so the usable depth is 0.13 m and
                 the duck's footprint still blocks the passage.
``bay_open``     a full-depth 0.34 m recess, empty.  Usable.
``bay_far``      the same on the opposite wall, further down.  Usable.

The rejections are therefore geometric, not scripted: the scorer computes each
bay's usable depth from the scene and refuses the two that cannot clear the
passage.  A viewer can see the difference — one bay is visibly a dent, one is
visibly full of boxes.

Every wall, marker, crate and pedestrian is ``contype="0" conaffinity="0"``.
The adults are MOCAP bodies posed analytically each tick: kinematically
scripted, never dynamically simulated, and physically unable to touch or push
the robot.  They add no degrees of freedom to the floating base, so the walking
policy sees exactly the robot it was trained on, and a completed pull-over can
never be the result of a person nudging the duck into a recess.

THE WALLS ARE ALSO NON-COLLIDING, and that is a deliberate, load-bearing
choice.  If the walls could collide, "the duck stayed inside the corridor"
would be enforced by physics rather than demonstrated by control, and a duck
that scraped along a wall for ten seconds would still pass a contact gate.
With non-colliding walls the corridor is a constraint the CONTROLLER has to
respect, and the acceptance gate measures the real surface distance between the
robot's geoms and the wall geoms every tick.

Generated rather than hand-written so the recesses, the crates and the keyframe
padding stay consistent with ``scripts/corridor.py`` instead of being restated
by hand.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from corridor import (  # noqa: E402
    ALCOVES,
    CEILING_LIGHTS,
    CORRIDOR_HALF_WIDTH,
    CORRIDOR_X_MAX,
    CORRIDOR_X_MIN,
    DESTINATION_HALF,
    DESTINATION_X,
    LOBBY_HALF_WIDTH,
    LOBBY_X_MAX,
    START_X,
    WALL_DOORS,
    WALL_HEIGHT,
    WALL_THICKNESS,
)
from people import PEDESTRIANS  # noqa: E402

HEADER = """<mujoco model="scene_narrow_corridor">
    <!-- narrow-corridor-etiquette: a tight indoor corridor with four side
         recesses.  GENERATED by tools/build_scene.py - edit that script, not
         this file.

         Every wall, crate, door and pedestrian is contype="0" conaffinity="0":
         kinematic scenery that cannot touch or push the robot.  The pedestrians
         are mocap bodies posed analytically each tick, so they add no degrees
         of freedom to the floating base and the walking policy sees exactly the
         robot it was trained on.  A completed pull-over can never be the result
         of a person pushing the duck into a recess, and staying inside the
         corridor is a property of the CONTROLLER rather than of collision
         geometry. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.70 0.70 0.70" ambient="0.40 0.40 0.40" specular="0 0 0" />
        <rgba haze="0.20 0.22 0.26 1" />
        <global azimuth="150" elevation="-24" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.20 0.22 0.28" rgb2="0.04 0.05 0.07"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.30 0.30 0.33" rgb2="0.24 0.24 0.27" markrgb="0.42 0.42 0.46"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="14 14" reflectance="0.06" />
        <material name="floormat" rgba="0.44 0.43 0.41 1" />
        <material name="lobbymat" rgba="0.50 0.49 0.47 1" />
        <material name="wallmat" rgba="0.72 0.71 0.68 1" />
        <material name="wallbandmat" rgba="0.30 0.36 0.44 1" />
        <material name="alcovemat" rgba="0.64 0.63 0.60 1" />
        <material name="openbaymat" rgba="0.30 0.72 0.42 1" />
        <material name="crateamat" rgba="0.68 0.48 0.24 1" />
        <material name="cratebmat" rgba="0.58 0.40 0.20 1" />
        <material name="doormat" rgba="0.36 0.30 0.26 1" />
        <material name="doorframemat" rgba="0.24 0.20 0.17 1" />
        <material name="lightmat" rgba="1.0 0.97 0.86 1" />
        <material name="centrelinemat" rgba="0.92 0.86 0.30 0.55" />
        <material name="passagemat" rgba="0.95 0.42 0.20 0.22" />
        <material name="destmat" rgba="0.20 0.92 0.48 0.40" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.10 0.13 0.22 1" />
        <material name="shoemat" rgba="0.05 0.05 0.06 1" />
        <material name="pipemat" rgba="0.52 0.54 0.58 1" />
"""

FOOTER_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 2.6" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="etiquette_rig" mocap="true" pos="0 0 0.20">
            <camera name="etiquette_camera" fovy="58" />
        </body>
"""


def _box(name: str, pos, size, material: str, extra: str = "") -> str:
    return (
        f'        <geom name="{name}" type="box" pos="{pos[0]:.4f} {pos[1]:.4f} '
        f'{pos[2]:.4f}" size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}" '
        f'material="{material}" contype="0" conaffinity="0"{extra} />\n'
    )


def floors() -> str:
    """Corridor floor slab, lobby slab, centreline paint and the destination."""
    parts = ["\n        <!-- floor slabs, paint -->\n"]
    corridor_len = 0.5 * (CORRIDOR_X_MAX - CORRIDOR_X_MIN)
    corridor_mid = 0.5 * (CORRIDOR_X_MAX + CORRIDOR_X_MIN)
    parts.append(_box("corridor_floor", (corridor_mid, 0.0, 0.0015),
                      (corridor_len, CORRIDOR_HALF_WIDTH + 0.40, 0.0015),
                      "floormat"))
    lobby_len = 0.5 * (LOBBY_X_MAX - CORRIDOR_X_MAX)
    parts.append(_box("lobby_floor",
                      (CORRIDOR_X_MAX + lobby_len, 0.0, 0.0012),
                      (lobby_len, LOBBY_HALF_WIDTH, 0.0012), "lobbymat"))
    # The corridor centreline, drawn as a dashed strip so the rejoin is
    # visually gradeable rather than only numerically.
    dash = 0.14
    x = CORRIDOR_X_MIN + 0.10
    index = 0
    while x < CORRIDOR_X_MAX:
        parts.append(_box(f"centreline_{index}", (x + dash, 0.0, 0.0032),
                          (dash, 0.012, 0.0032), "centrelinemat"))
        x += 2.6 * dash
        index += 1
    # The centre passage an adult needs: painted so a viewer can see the duck
    # get out of it and back into it.
    from corridor import CENTER_PASSAGE_HALF
    for sign, side in ((+1.0, "plus"), (-1.0, "minus")):
        parts.append(_box(
            f"passage_edge_{side}",
            (corridor_mid, sign * CENTER_PASSAGE_HALF, 0.0022),
            (corridor_len, 0.008, 0.0022), "passagemat"))
    parts.append(_box("destination", (DESTINATION_X, 0.0, 0.0040),
                      (DESTINATION_HALF, CORRIDOR_HALF_WIDTH - 0.01, 0.0040),
                      "destmat"))
    return "".join(parts)


def _wall_segments(side: int) -> list[tuple[float, float]]:
    """Contiguous x-spans of plain wall on one side, i.e. the gaps between bays."""
    mouths = sorted(a.x_span for a in ALCOVES if a.side == side)
    segments: list[tuple[float, float]] = []
    cursor = CORRIDOR_X_MIN
    for low, high in mouths:
        if low > cursor:
            segments.append((cursor, low))
        cursor = max(cursor, high)
    if cursor < CORRIDOR_X_MAX:
        segments.append((cursor, CORRIDOR_X_MAX))
    return segments


def walls() -> str:
    """Corridor walls, broken by the alcove mouths, plus each recess's shell."""
    parts = ["\n        <!-- corridor walls, broken by the alcove mouths -->\n"]
    half_t = 0.5 * WALL_THICKNESS
    for side, tag in ((+1, "plus"), (-1, "minus")):
        for index, (low, high) in enumerate(_wall_segments(side)):
            length = 0.5 * (high - low)
            if length <= 1e-6:
                continue
            mid = 0.5 * (high + low)
            parts.append(_box(
                f"wall_{tag}_{index}",
                (mid, side * (CORRIDOR_HALF_WIDTH + half_t), 0.5 * WALL_HEIGHT),
                (length, half_t, 0.5 * WALL_HEIGHT), "wallmat"))
            # A dark band at duck-eye height so the PiP has a horizon reference.
            parts.append(_box(
                f"wallband_{tag}_{index}",
                (mid, side * (CORRIDOR_HALF_WIDTH - 0.004), 0.215),
                (length, 0.004, 0.020), "wallbandmat"))

    parts.append("\n        <!-- alcove shells: back wall and two cheeks -->\n")
    for alcove in ALCOVES:
        low, high = alcove.x_span
        outer = alcove.outer_y
        side = alcove.side
        half_len = alcove.half_length_x
        # back wall of the recess
        parts.append(_box(
            f"{alcove.name}_back",
            (alcove.center_x, side * (outer + half_t), 0.5 * WALL_HEIGHT),
            (half_len + WALL_THICKNESS, half_t, 0.5 * WALL_HEIGHT), "alcovemat"))
        # the two cheeks joining the recess back to the corridor line
        cheek_len = 0.5 * (outer - CORRIDOR_HALF_WIDTH)
        cheek_mid = side * (CORRIDOR_HALF_WIDTH + cheek_len)
        for end, x_edge in (("lo", low), ("hi", high)):
            parts.append(_box(
                f"{alcove.name}_cheek_{end}",
                (x_edge + (half_t if end == "lo" else -half_t),
                 cheek_mid, 0.5 * WALL_HEIGHT),
                (half_t, max(cheek_len, 1e-4), 0.5 * WALL_HEIGHT), "alcovemat"))
        # floor patch, tinted green where the recess is genuinely usable
        material = "openbaymat" if alcove.clears_passage else "alcovemat"
        patch_half = 0.5 * (outer - CORRIDOR_HALF_WIDTH)
        parts.append(_box(
            f"{alcove.name}_floor",
            (alcove.center_x, side * (CORRIDOR_HALF_WIDTH + patch_half), 0.0025),
            (half_len, max(patch_half, 1e-4), 0.0025), material))
        # the obstruction, where there is one
        if alcove.blocked_from is not None:
            crate_half = 0.5 * (outer - alcove.blocked_from)
            crate_mid = side * (alcove.blocked_from + crate_half)
            for level, (height, half_x, mat) in enumerate((
                (0.115, half_len - 0.04, "crateamat"),
                (0.085, half_len - 0.11, "cratebmat"),
            )):
                base = 0.0 if level == 0 else 0.230
                parts.append(_box(
                    f"{alcove.name}_crate_{level}",
                    (alcove.center_x + (0.0 if level == 0 else 0.03),
                     crate_mid, base + height),
                    (max(half_x, 0.05), max(crate_half, 0.02), height), mat))
    return "".join(parts)


def furniture() -> str:
    """Doors and wall-top light rails: depth cues, all non-colliding.

    MEASURED FROM THE PREVIEW, and a presentation constraint the scene has to
    satisfy rather than a decoration:

    * the first draft ran two pipe capsules down the corridor at z = 0.545.
      From the only camera angle that shows a 0.42 m corridor at all - high and
      behind, looking down its length - those pipes cut straight across the
      frame and hid the duck for most of the rollout;
    * the ceiling lights were strips on the corridor CENTRELINE, directly above
      the robot, so the same camera looked through them at its own subject.

    Both now sit over the WALLS instead of over the corridor, which keeps the
    depth cue and leaves the corridor itself unobstructed.
    """
    parts = ["\n        <!-- doors, wall-top light rails -->\n"]
    for name, x, side in WALL_DOORS:
        y = side * (CORRIDOR_HALF_WIDTH + 0.002)
        parts.append(_box(f"{name}_frame", (x, y, 0.255),
                          (0.185, 0.006, 0.255), "doorframemat"))
        parts.append(_box(f"{name}_leaf",
                          (x, side * (CORRIDOR_HALF_WIDTH - 0.004), 0.243),
                          (0.163, 0.004, 0.243), "doormat"))
    half_t = 0.5 * WALL_THICKNESS
    for index, x in enumerate(CEILING_LIGHTS):
        for side, tag in ((+1, "plus"), (-1, "minus")):
            parts.append(_box(
                f"ceil_light_{tag}_{index}",
                (x, side * (CORRIDOR_HALF_WIDTH + half_t), WALL_HEIGHT + 0.006),
                (0.14, half_t, 0.006), "lightmat"))
    # Lobby back wall, so the far end reads as a room rather than a void.
    parts.append(_box("lobby_back", (LOBBY_X_MAX, 0.0, 0.62),
                      (0.06, LOBBY_HALF_WIDTH, 0.62), "wallmat"))
    return "".join(parts)


def marker_blocks() -> str:
    """Mocap discs marking the selected alcove and the predicted meeting point."""
    markers = (
        ("selected_marker", "0.075 0.004", "openbaymat", 0.011),
        ("conflict_marker", "0.055 0.004", "passagemat", 0.012),
    )
    parts = ["\n        <!-- decision markers: mocap discs, non-colliding -->\n"]
    for name, size, material, z in markers:
        parts.append(
            f'        <body name="{name}" mocap="true" pos="0 0 {z:.3f}">\n'
            f'            <geom name="{name}_disc" type="cylinder" size="{size}"'
            f' material="{material}" contype="0" conaffinity="0" />\n'
            f"        </body>\n"
        )
    return "".join(parts)


def pedestrian_block(name: str, shirt: str) -> str:
    """One adult: torso, head, face flash, two hinged legs, two hinged arms."""
    lines = [
        f'        <body name="person_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_torso" type="capsule"'
        f' fromto="0 0 -0.10 0 0 0.16" size="0.078" material="{name}_shirt"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere" pos="0 0 0.255"'
        f' size="0.064" material="skinmat" contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere" pos="0.060 0 0.252"'
        f' size="0.019" material="{name}_shirt" contype="0" conaffinity="0" />',
    ]
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}" pos="0 {sy:+.3f} -0.10">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0"'
            f' range="-40 40" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 -0.26" size="0.033"'
            f' material="trousermat" contype="0" conaffinity="0" />'
            f'<geom type="capsule" fromto="0 0 -0.26 0.072 0 -0.272" size="0.035"'
            f' material="shoemat" contype="0" conaffinity="0" /></body>'
        )
    for side, sy in (("l", 0.078), ("r", -0.078)):
        lines.append(
            f'            <body name="{name}_arm_{side}" pos="0 {sy:+.3f} 0.115">'
            f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
            f' range="-32 32" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 -0.205" size="0.026"'
            f' material="skinmat" contype="0" conaffinity="0" /></body>'
        )
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    materials = "".join(
        f'        <material name="{p.name}_shirt" rgba="{p.rgba}" />\n'
        for p in PEDESTRIANS
    )
    parts = [HEADER + materials + FOOTER_OPEN]
    parts.append(floors())
    parts.append(walls())
    parts.append(furniture())
    parts.append(marker_blocks())
    parts.append("\n        <!-- adults: mocap, non-colliding, scripted -->\n")
    for person in PEDESTRIANS:
        parts.append(pedestrian_block(person.name, person.rgba))
    parts.append("    </worldbody>\n\n")

    # 7 free-joint qpos + 14 actuated joints + 4 hinges per pedestrian.
    hinge_pad = " ".join(["0"] * (4 * len(PEDESTRIANS)))
    stand = (
        f"        {START_X} 0 0.12 1 0 0 0\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 4 * len(PEDESTRIANS)))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="{START_X} 0 0.12 1 0 0 0 {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = (Path(__file__).resolve().parents[1] / "assets"
           / "scene_narrow_corridor.xml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
