#!/usr/bin/env python3
"""Emit assets/scene_slalom.xml — a broad depot floor with static obstacles,
moving traffic and a visible arrival band.

GENERATED from ``scripts/slalom_course.py`` and ``scripts/slalom_cast.py``
rather than hand-written, so the surfaces the clearance gate grades, the bodies
the planner prunes against, the actors the choreography poses and the geometry
the camera ray-casts through are all the SAME objects.  Moving a crate moves it
everywhere at once.

Everything except the robot is ``contype="0" conaffinity="0"``: kinematic
scenery that cannot touch or push the robot.  The actors are mocap bodies posed
analytically each tick, so they add no degrees of freedom to the floating base
and the walking policy sees exactly the robot it was trained on.  A step the
duck takes can therefore never be the result of somebody nudging it.

THE STATIC OBSTACLES BEING NON-COLLIDING IS DELIBERATE.  If they collided,
"the duck never walked through a crate" would be enforced by the contact solver
rather than demonstrated by the planner, and a duck that ground its way along a
pallet for five seconds would still pass.  With non-colliding scenery every
slalom claim is a property of the SOFTWARE, graded by measured surface clearance
every control tick.

CART AND BOX GEOMETRY IS REAL, NOT A LABEL.  A cart is a box on two wheels
0.30 m ahead of its pusher and a carried box is a box at chest height 0.15 m in
front of its carrier, so both genuinely widen the body the duck has to clear and
the per-tick clearance probe measures against those geoms.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from slalom_cast import (  # noqa: E402
    ACTORS,
    BASE_ORIGIN_Z,
    BOX_DZ,
    BOX_HALF,
    CART_HALF,
    CART_WHEEL_DY,
    CART_WHEEL_R,
    CART_Z,
)
from slalom_course import (  # noqa: E402
    DUCK_START_XY,
    DUCK_START_YAW_DEG,
    FLOOR_HALF,
    GOAL_BAND_HALF,
    GOAL_BEACON_H,
    GOAL_BEACON_R,
    GOAL_BEACON_XY,
    GOAL_PYLON_DY,
    GOAL_PYLON_H,
    GOAL_PYLON_R,
    GOAL_XY,
    STATIC_OBSTACLES,
    WALL_HALF_Z,
    WALL_T,
)

HEADER = """<mujoco model="scene_slalom">
    <!-- dynamic-slalom: a broad depot floor crossed by moving pedestrians,
         rolling carts and carried boxes, with static crates, pallets and cones
         between the duck and a painted arrival band.
         GENERATED by tools/build_scene.py - edit that script, not this file.

         Every wall, crate, pallet, cone, pylon, beacon, cart, box and person is
         contype="0" conaffinity="0": kinematic scenery that cannot touch or
         push the robot.  Choosing a corridor and reaching the goal are
         therefore properties of the PLANNER and the CONTROLLER, graded by
         measured surface clearance and by where the trunk actually ended up,
         not by the contact solver. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.80 0.80 0.80" ambient="0.47 0.47 0.47" specular="0 0 0" />
        <rgba haze="0.18 0.20 0.25 1" />
        <global azimuth="150" elevation="-30" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.17 0.19 0.25" rgb2="0.04 0.05 0.08"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.28 0.28 0.31" rgb2="0.23 0.23 0.26" markrgb="0.38 0.38 0.42"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="20 20" reflectance="0.05" />
        <material name="hallmat" rgba="0.45 0.45 0.43 1" />
        <material name="wallmat" rgba="0.69 0.68 0.65 1" />
        <material name="cratemat" rgba="0.50 0.38 0.24 1" />
        <material name="palletmat" rgba="0.42 0.34 0.22 1" />
        <material name="conemat" rgba="0.92 0.42 0.12 1" />
        <material name="goalmat" rgba="0.26 0.90 0.52 0.42" />
        <material name="pylonmat" rgba="0.96 0.82 0.20 1" />
        <material name="beaconmat" rgba="0.30 0.94 0.60 1" />
        <material name="lanemat" rgba="0.36 0.78 0.98 0.20" />
        <material name="cartmat" rgba="0.58 0.60 0.66 1" />
        <material name="cartwheelmat" rgba="0.14 0.14 0.16 1" />
        <material name="boxmat" rgba="0.78 0.66 0.42 1" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.12 0.15 0.22 1" />
        <material name="shoemat" rgba="0.05 0.05 0.06 1" />
        <material name="routemat" rgba="0.36 0.78 0.98 0.45" />
        <material name="leftmat" rgba="0.42 0.86 0.98 0.34" />
        <material name="rightmat" rgba="0.98 0.72 0.36 0.34" />
        <material name="predmat" rgba="0.98 0.36 0.42 0.30" />
        <material name="trailmat" rgba="0.62 0.52 0.95 0.32" />
        <material name="holdmat" rgba="0.24 0.94 0.52 0.45" />
"""

WORLD_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.8" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="slalom_rig" mocap="true" pos="0 0 0.20">
            <camera name="slalom_camera" fovy="58" />
        </body>
"""

# How many world-space markers the scene carries.
ROUTE_DISCS = 26
TRAIL_DISCS = 18
# Predicted-occupancy discs: one per predicted horizon sample, per side.
PRED_DISCS = 10
CORRIDOR_DISCS = 8


def _box(name, pos, size, material) -> str:
    return (
        f'        <geom name="{name}" type="box" pos="{pos[0]:.4f} {pos[1]:.4f} '
        f'{pos[2]:.4f}" size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def _cyl(name, pos, radius, half_h, material) -> str:
    return (
        f'        <geom name="{name}" type="cylinder" pos="{pos[0]:.4f} '
        f'{pos[1]:.4f} {pos[2]:.4f}" size="{radius:.4f} {half_h:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def hall() -> str:
    """Depot floor slab and the four perimeter walls."""
    parts = ["\n        <!-- depot floor and perimeter walls -->\n"]
    parts.append(_box("hall_floor", (0.0, 0.0, 0.0015),
                      (FLOOR_HALF[0], FLOOR_HALF[1], 0.0015), "hallmat"))
    for tag, sign in (("e", +1.0), ("w", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (sign * (FLOOR_HALF[0] + WALL_T), 0.0, WALL_HALF_Z),
            (WALL_T, FLOOR_HALF[1] + 2 * WALL_T, WALL_HALF_Z), "wallmat"))
    for tag, sign in (("n", +1.0), ("s", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (0.0, sign * (FLOOR_HALF[1] + WALL_T), WALL_HALF_Z),
            (FLOOR_HALF[0] + 2 * WALL_T, WALL_T, WALL_HALF_Z), "wallmat"))
    return "".join(parts)


def obstacles() -> str:
    """Every static obstacle in :data:`slalom_course.STATIC_OBSTACLES`.

    Geom names come from the obstacle's own name, so
    ``rollout_slalom.scenery_geom_names`` collects them from the model rather
    than from a hand-kept list and a new obstacle cannot silently escape the
    clearance gate.
    """
    parts = ["\n        <!-- static crates, pallets and cones -->\n"]
    for obstacle in STATIC_OBSTACLES:
        half_h = 0.5 * obstacle.height_m
        if obstacle.kind == "cylinder":
            parts.append(_cyl(
                obstacle.name,
                (obstacle.center[0], obstacle.center[1], half_h),
                obstacle.radius, half_h, obstacle.material))
        else:
            parts.append(_box(
                obstacle.name,
                (obstacle.center[0], obstacle.center[1], half_h),
                (obstacle.half[0], obstacle.half[1], half_h),
                obstacle.material))
    return "".join(parts)


def goal_block() -> str:
    """The painted arrival band, its two pylons and the beacon post.

    Real world geometry rather than a HUD annotation, so the destination the
    duck walks to is a thing a viewer can see it walk to, and the beacon is what
    the head camera's goal-visibility measurement samples.
    """
    parts = ["\n        <!-- the destination: painted band, pylons, beacon -->\n"]
    parts.append(_box("goal_band", (GOAL_XY[0], GOAL_XY[1], 0.006),
                      (GOAL_BAND_HALF[0], GOAL_BAND_HALF[1], 0.006), "goalmat"))
    parts.append(_box("lane_stripe", (0.0, 0.0, 0.003),
                      (FLOOR_HALF[0] - 0.40, 0.035, 0.003), "lanemat"))
    for tag, sign in (("n", +1.0), ("s", -1.0)):
        parts.append(_cyl(
            f"goal_pylon_{tag}",
            (GOAL_XY[0], GOAL_XY[1] + sign * GOAL_PYLON_DY, 0.5 * GOAL_PYLON_H),
            GOAL_PYLON_R, 0.5 * GOAL_PYLON_H, "pylonmat"))
    parts.append(_cyl(
        "goal_beacon", (GOAL_BEACON_XY[0], GOAL_BEACON_XY[1],
                        0.5 * GOAL_BEACON_H),
        GOAL_BEACON_R, 0.5 * GOAL_BEACON_H, "beaconmat"))
    return "".join(parts)


def markers() -> str:
    """Mocap discs: the plan, the two candidate corridors, the predictions."""
    entries = [(f"route_{i}", "routemat", 0.034, 0.004)
               for i in range(ROUTE_DISCS)]
    entries += [(f"trail_{i}", "trailmat", 0.036, 0.004)
                for i in range(TRAIL_DISCS)]
    entries += [(f"left_{i}", "leftmat", 0.044, 0.005)
                for i in range(CORRIDOR_DISCS)]
    entries += [(f"right_{i}", "rightmat", 0.044, 0.005)
                for i in range(CORRIDOR_DISCS)]
    entries += [(f"pred_{i}", "predmat", 0.070, 0.004)
                for i in range(PRED_DISCS)]
    entries += [("goal_marker", "holdmat", 0.120, 0.007)]
    parts = ["\n        <!-- plan, corridor and prediction markers -->\n"]
    for name, material, radius, half_h in entries:
        parts.append(
            f'        <body name="{name}" mocap="true" pos="0 0 -3.0">\n'
            f'            <geom name="{name}_disc" type="cylinder"'
            f' size="{radius:.3f} {half_h:.3f}" material="{material}"'
            f' contype="0" conaffinity="0" />\n'
            f"        </body>\n")
    return "".join(parts)


def actor_block(actor) -> str:
    """One moving body, SCALED BY STATURE, with its cart or box if it has one."""
    s = actor.stature
    name = actor.name
    lines = [
        f'        <body name="actor_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_torso" type="capsule"'
        f' fromto="0 0 {-0.10 * s:.4f} 0 0 {0.16 * s:.4f}"'
        f' size="{0.078 * s:.4f}" material="{name}_shirt"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere"'
        f' pos="0 0 {0.255 * s:.4f}" size="{0.064 * s:.4f}" material="skinmat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere"'
        f' pos="{0.060 * s:.4f} 0 {0.252 * s:.4f}" size="{0.019 * s:.4f}"'
        f' material="{name}_shirt" contype="0" conaffinity="0" />',
    ]
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}"'
            f' pos="0 {sy * s:+.4f} {-0.10 * s:.4f}">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.26 * s:.4f}"'
            f' size="{0.033 * s:.4f}" material="trousermat"'
            f' contype="0" conaffinity="0" />'
            f'<geom type="capsule"'
            f' fromto="0 0 {-0.26 * s:.4f} {0.072 * s:.4f} 0 {-0.272 * s:.4f}"'
            f' size="{0.035 * s:.4f}" material="shoemat"'
            f' contype="0" conaffinity="0" /></body>')
    # A carrier's arms are forward round the box; everybody else's swing.
    arm_z = 0.115 * s
    for side, sy in (("l", 0.078), ("r", -0.078)):
        lines.append(
            f'            <body name="{name}_arm_{side}"'
            f' pos="0 {sy * s:+.4f} {arm_z:.4f}">'
            f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.205 * s:.4f}"'
            f' size="{0.026 * s:.4f}" material="skinmat"'
            f' contype="0" conaffinity="0" /></body>')

    if actor.carries_cart:
        from slalom_cast import CART_AHEAD_M
        lines.append(
            f'            <geom name="{name}_cart" type="box"'
            f' pos="{CART_AHEAD_M:.4f} 0 {CART_Z:.4f}"'
            f' size="{CART_HALF[0]:.4f} {CART_HALF[1]:.4f} {CART_HALF[2]:.4f}"'
            f' material="cartmat" contype="0" conaffinity="0" />')
        lines.append(
            f'            <geom name="{name}_cart_handle" type="capsule"'
            f' fromto="{CART_AHEAD_M - CART_HALF[0]:.4f} 0 {CART_Z:.4f}'
            f' {0.06:.4f} 0 {CART_Z + 0.06:.4f}" size="0.014"'
            f' material="cartwheelmat" contype="0" conaffinity="0" />')
        for tag, sy in (("l", +CART_WHEEL_DY), ("r", -CART_WHEEL_DY)):
            lines.append(
                f'            <geom name="{name}_wheel_{tag}" type="sphere"'
                f' pos="{CART_AHEAD_M:.4f} {sy:+.4f} {CART_WHEEL_R:.4f}"'
                f' size="{CART_WHEEL_R:.4f}" material="cartwheelmat"'
                f' contype="0" conaffinity="0" />')
    if actor.carries_box:
        from slalom_cast import BOX_AHEAD_M
        lines.append(
            f'            <geom name="{name}_box" type="box"'
            f' pos="{BOX_AHEAD_M:.4f} 0 {BOX_DZ * s:.4f}"'
            f' size="{BOX_HALF[0]:.4f} {BOX_HALF[1]:.4f} {BOX_HALF[2]:.4f}"'
            f' material="boxmat" contype="0" conaffinity="0" />')
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    materials = "".join(
        f'        <material name="{a.name}_shirt" rgba="{a.rgba}" />\n'
        for a in ACTORS)
    parts = [HEADER + materials + WORLD_OPEN,
             hall(), obstacles(), goal_block(), markers(),
             "\n        <!-- moving traffic: mocap, non-colliding -->\n"]
    parts.extend(actor_block(a) for a in ACTORS)
    parts.append("    </worldbody>\n\n")

    yaw = math.radians(DUCK_START_YAW_DEG)
    quat = (math.cos(0.5 * yaw), 0.0, 0.0, math.sin(0.5 * yaw))
    base = (f"{DUCK_START_XY[0]:.4f} {DUCK_START_XY[1]:.4f} 0.12 "
            f"{quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f} {quat[3]:.6f}")
    hinge_pad = " ".join(["0"] * (4 * len(ACTORS)))
    stand = (
        f"        {base}\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 4 * len(ACTORS)))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="{base} {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = (Path(__file__).resolve().parents[1] / "assets" / "scene_slalom.xml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  actors={len(ACTORS)}  static_obstacles={len(STATIC_OBSTACLES)}  "
          f"goal={GOAL_XY}  base_origin_z={BASE_ORIGIN_Z}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
