#!/usr/bin/env python3
"""Emit assets/scene_door_lift.xml — a concourse, an automatic door, a lift
lobby and a through-car cabin.

GENERATED from ``scripts/lobby_layout.py``, ``scripts/lobby_doors.py`` and
``scripts/etiquette_cast.py`` rather than hand-written, so the surfaces the
clearance gate grades, the apertures the zone module derives from, the leaves
the door state poses and the bodies the camera ray-casts through are all the
SAME objects.  A scene edit that widens the lift doors widens them everywhere at
once.

Everything except the robot is ``contype="0" conaffinity="0"``: kinematic
scenery that cannot touch or push the robot.  The people are mocap bodies posed
analytically each tick, so they add no degrees of freedom to the floating base
and the walking policy sees exactly the robot it was trained on.  A step the
duck takes can therefore never be the result of somebody nudging it.

THE WALLS AND DOORS BEING NON-COLLIDING IS DELIBERATE.  If they collided,
"the duck did not walk through a closed door" would be enforced by the contact
solver rather than demonstrated by the behavior, and a duck that ground its way
along a leaf for five seconds would still pass.  With non-colliding scenery,
every etiquette claim is a property of the SOFTWARE, graded by measured surface
clearance every control tick and by measured aperture crossings.

THE DOOR LEAVES ARE MOCAP BODIES, not static geoms, because they move.  Their
positions come from ``lobby_doors.DoorState.leaf_offsets`` every tick, so the
picture and the measured clear gap cannot disagree.

PERSON GEOMETRY IS SCALED BY STATURE, so a shorter adult genuinely has a lower
head and the camera's topmost sample of them is genuinely nearer the ground.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from etiquette_cast import BASE_ORIGIN_Z, PEOPLE  # noqa: E402
from etiquette_states import DUCK_START_XY, DUCK_START_YAW_DEG  # noqa: E402
from lobby_doors import APERTURES  # noqa: E402
from lobby_layout import (  # noqa: E402
    CABIN_H,
    CABIN_X,
    CABIN_Y,
    DOOR_LEAF_HALF_T,
    DOOR_LEAF_HALF_W,
    FLOOR_HALF,
    LIFT_LEAF_HALF_T,
    LIFT_LEAF_HALF_W,
    PARTITION_H,
    REAR_LEAF_HALF_T,
    REAR_LEAF_HALF_W,
    STATIC_OBSTACLES,
    WALL_HALF_Z,
    WALL_T,
)

HEADER = """<mujoco model="scene_door_lift">
    <!-- door-elevator-etiquette: a concourse divided by an automatic door, a
         lift lobby, and a through-car cabin with doors front and rear.
         GENERATED by tools/build_scene.py - edit that script, not this file.

         Every wall, jamb, cabin panel, door leaf, bench, planter, crate and
         person is contype="0" conaffinity="0": kinematic scenery that cannot
         touch or push the robot.  Yielding at a doorway and standing clear of a
         lift are therefore properties of the STATE MACHINE and the CONTROLLER,
         graded by measured surface clearance and measured aperture crossings,
         not by the contact solver.

         The shaft and cabin panels are CUTAWAY height (1.35 m and 1.15 m), well
         above the 0.90 m occlusion threshold and far above the 0.70 m topmost
         camera sample of an adult, so the duck's own head camera is occluded by
         them exactly as it would be by full-height walls.  Only the overhead
         spectator camera sees into the car. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.80 0.80 0.80" ambient="0.47 0.47 0.47" specular="0 0 0" />
        <rgba haze="0.18 0.20 0.25 1" />
        <global azimuth="150" elevation="-30" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.17 0.19 0.25" rgb2="0.04 0.05 0.08"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.28 0.28 0.31" rgb2="0.23 0.23 0.26" markrgb="0.38 0.38 0.42"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="20 20" reflectance="0.05" />
        <material name="hallmat" rgba="0.47 0.46 0.44 1" />
        <material name="wallmat" rgba="0.69 0.68 0.65 1" />
        <material name="doormat" rgba="0.34 0.37 0.45 1" />
        <material name="shaftmat" rgba="0.30 0.38 0.44 1" />
        <material name="cabinmat" rgba="0.40 0.42 0.47 1" />
        <material name="cabinfloormat" rgba="0.33 0.35 0.40 1" />
        <material name="leafmat" rgba="0.62 0.72 0.80 1" />
        <material name="liftleafmat" rgba="0.70 0.76 0.82 1" />
        <material name="benchmat" rgba="0.44 0.33 0.24 1" />
        <material name="plantermat" rgba="0.37 0.29 0.21 1" />
        <material name="cratemat" rgba="0.50 0.38 0.24 1" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.12 0.15 0.22 1" />
        <material name="shoemat" rgba="0.05 0.05 0.06 1" />
        <material name="routemat" rgba="0.36 0.78 0.98 0.45" />
        <material name="wpmat" rgba="0.98 0.80 0.24 0.60" />
        <material name="thresholdmat" rgba="0.98 0.42 0.30 0.30" />
        <material name="passagemat" rgba="0.98 0.62 0.20 0.28" />
        <material name="holdmat" rgba="0.24 0.94 0.52 0.45" />
        <material name="trailmat" rgba="0.62 0.52 0.95 0.32" />
"""

WORLD_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.8" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="lobby_rig" mocap="true" pos="0 0 0.20">
            <camera name="lobby_camera" fovy="58" />
        </body>
"""

# How many world-space markers the scene carries.
ROUTE_DISCS = 30
WAYPOINT_DISCS = 10
TRAIL_DISCS = 16


def _box(name, pos, size, material) -> str:
    return (
        f'        <geom name="{name}" type="box" pos="{pos[0]:.4f} {pos[1]:.4f} '
        f'{pos[2]:.4f}" size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def hall() -> str:
    """Concourse floor slab and the four perimeter walls."""
    parts = ["\n        <!-- concourse floor and perimeter walls -->\n"]
    parts.append(_box("hall_floor", (0.0, 0.0, 0.0015),
                      (FLOOR_HALF[0], FLOOR_HALF[1], 0.0015), "hallmat"))
    for tag, sign in (("e", +1.0), ("w", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (sign * (FLOOR_HALF[0] + WALL_T), 0.0, WALL_HALF_Z),
            (WALL_T, FLOOR_HALF[1] + 2 * WALL_T, WALL_HALF_Z), "wallmat"))
    for tag, sign in (("n", +1.0), ("s", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (0.0, sign * (FLOOR_HALF[1] + WALL_T), WALL_HALF_Z),
            (FLOOR_HALF[0] + 2 * WALL_T, WALL_T, WALL_HALF_Z), "wallmat"))
    # A tinted slab under the cabin, so the car reads as a car in the video and
    # the viewer can see the duck cross its sill.
    parts.append(_box(
        "cabin_floor",
        (0.5 * (CABIN_X[0] + CABIN_X[1]), 0.5 * (CABIN_Y[0] + CABIN_Y[1]), 0.004),
        (0.5 * (CABIN_X[1] - CABIN_X[0]), 0.5 * (CABIN_Y[1] - CABIN_Y[0]), 0.004),
        "cabinfloormat"))
    return "".join(parts)


def structure() -> str:
    """Every static obstacle in :data:`lobby_layout.STATIC_OBSTACLES`.

    Geom names come from the obstacle's own name, so
    ``rollout_etiquette.scenery_geom_names`` collects them from the model rather
    than from a hand-kept list and a new obstacle cannot silently escape the
    clearance gate.
    """
    parts = ["\n        <!-- jambs, cabin panels and lobby furniture -->\n"]
    for obstacle in STATIC_OBSTACLES:
        half_h = 0.5 * obstacle.height_m
        parts.append(_box(
            obstacle.name,
            (obstacle.center[0], obstacle.center[1], half_h),
            (obstacle.half[0], obstacle.half[1], half_h),
            obstacle.material))
    return "".join(parts)


def leaves() -> str:
    """The six sliding door leaves, as mocap bodies.

    Mocap rather than static because they MOVE: ``lobby_doors`` poses them from
    the measured open fraction every tick, so the picture and the measured clear
    gap are the same number.
    """
    spec = {
        "concourse_door": (DOOR_LEAF_HALF_W, DOOR_LEAF_HALF_T, PARTITION_H,
                           "leafmat"),
        "lift_front": (LIFT_LEAF_HALF_W, LIFT_LEAF_HALF_T, PARTITION_H,
                       "liftleafmat"),
        "lift_rear": (REAR_LEAF_HALF_W, REAR_LEAF_HALF_T, CABIN_H,
                      "liftleafmat"),
    }
    parts = ["\n        <!-- sliding door leaves: mocap, posed from the open "
             "fraction -->\n"]
    for name, (half_w, half_t, height, material) in spec.items():
        half_h = 0.5 * height
        for side in ("s", "n"):
            parts.append(
                f'        <body name="leaf_{name}_{side}" mocap="true"'
                f' pos="0 0 -3.0">\n'
                f'            <geom name="leaf_{name}_{side}_panel" type="box"'
                f' size="{half_t:.4f} {half_w:.4f} {half_h:.4f}"'
                f' material="{material}" contype="0" conaffinity="0" />\n'
                f"        </body>\n")
    return "".join(parts)


def markers() -> str:
    """Mocap discs: the duck's route, its waypoints, the zones and the trail."""
    entries = [(f"route_{i}", "routemat", 0.036, 0.004)
               for i in range(ROUTE_DISCS)]
    entries += [(f"wp_{i}", "wpmat", 0.062, 0.006) for i in range(WAYPOINT_DISCS)]
    entries += [(f"trail_{i}", "trailmat", 0.038, 0.004)
                for i in range(TRAIL_DISCS)]
    entries += [("hold_marker", "holdmat", 0.140, 0.007),
                ("wait_marker", "holdmat", 0.120, 0.007)]
    parts = ["\n        <!-- route and decision markers: mocap discs -->\n"]
    for name, material, radius, half_h in entries:
        parts.append(
            f'        <body name="{name}" mocap="true" pos="0 0 -3.0">\n'
            f'            <geom name="{name}_disc" type="cylinder"'
            f' size="{radius:.3f} {half_h:.3f}" material="{material}"'
            f' contype="0" conaffinity="0" />\n'
            f"        </body>\n")
    return "".join(parts)


def zone_decals() -> str:
    """Flat coloured decals showing the threshold bands and the exit passage.

    Real world geometry rather than a HUD annotation, so a viewer can see the
    zone the duck stays out of drawn on the floor it stays off.  They are thin
    slabs a few millimetres proud of the floor and hide nothing.
    """
    from etiquette_zones import DOOR_THRESHOLD, LIFT_PASSAGE, LIFT_THRESHOLD

    parts = ["\n        <!-- etiquette zones, drawn on the floor -->\n"]
    for band, material in ((DOOR_THRESHOLD, "thresholdmat"),
                           (LIFT_THRESHOLD, "thresholdmat"),
                           (LIFT_PASSAGE, "passagemat")):
        center = band.center()
        parts.append(_box(
            f"zone_{band.name}", (float(center[0]), float(center[1]), 0.006),
            (0.5 * (band.x_range[1] - band.x_range[0]),
             0.5 * (band.y_range[1] - band.y_range[0]), 0.006),
            material))
    return "".join(parts)


def person_block(person) -> str:
    """One adult, SCALED BY STATURE so height is geometry, not a label."""
    s = person.stature
    name = person.name
    lines = [
        f'        <body name="person_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_torso" type="capsule"'
        f' fromto="0 0 {-0.10 * s:.4f} 0 0 {0.16 * s:.4f}"'
        f' size="{0.078 * s:.4f}" material="{name}_shirt"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere"'
        f' pos="0 0 {0.255 * s:.4f}" size="{0.064 * s:.4f}" material="skinmat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere"'
        f' pos="{0.060 * s:.4f} 0 {0.252 * s:.4f}" size="{0.019 * s:.4f}"'
        f' material="{name}_shirt" contype="0" conaffinity="0" />',
    ]
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}"'
            f' pos="0 {sy * s:+.4f} {-0.10 * s:.4f}">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.26 * s:.4f}"'
            f' size="{0.033 * s:.4f}" material="trousermat"'
            f' contype="0" conaffinity="0" />'
            f'<geom type="capsule"'
            f' fromto="0 0 {-0.26 * s:.4f} {0.072 * s:.4f} 0 {-0.272 * s:.4f}"'
            f' size="{0.035 * s:.4f}" material="shoemat"'
            f' contype="0" conaffinity="0" /></body>')
    for side, sy in (("l", 0.078), ("r", -0.078)):
        lines.append(
            f'            <body name="{name}_arm_{side}"'
            f' pos="0 {sy * s:+.4f} {0.115 * s:.4f}">'
            f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.205 * s:.4f}"'
            f' size="{0.026 * s:.4f}" material="skinmat"'
            f' contype="0" conaffinity="0" /></body>')
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    materials = "".join(
        f'        <material name="{p.name}_shirt" rgba="{p.rgba}" />\n'
        for p in PEOPLE)
    parts = [HEADER + materials + WORLD_OPEN,
             hall(), structure(), zone_decals(), leaves(), markers(),
             "\n        <!-- people: mocap, non-colliding -->\n"]
    parts.extend(person_block(p) for p in PEOPLE)
    parts.append("    </worldbody>\n\n")

    yaw = math.radians(DUCK_START_YAW_DEG)
    quat = (math.cos(0.5 * yaw), 0.0, 0.0, math.sin(0.5 * yaw))
    base = (f"{DUCK_START_XY[0]:.4f} {DUCK_START_XY[1]:.4f} 0.12 "
            f"{quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f} {quat[3]:.6f}")
    hinge_pad = " ".join(["0"] * (4 * len(PEOPLE)))
    stand = (
        f"        {base}\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 4 * len(PEOPLE)))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="{base} {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = (Path(__file__).resolve().parents[1] / "assets"
           / "scene_door_lift.xml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  people={len(PEOPLE)}  static_obstacles={len(STATIC_OBSTACLES)}  "
          f"apertures={len(APERTURES)}  base_origin_z={BASE_ORIGIN_Z}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
