#!/usr/bin/env python3
"""The scene's fixed XML preamble: visual settings, materials, the camera rig.

Held apart from the geometry emitters so a material or a lighting change never
touches the code that computes positions.
"""

from __future__ import annotations

HEADER = """<mujoco model="scene_queue_politely">
    <!-- queue-politely: a service counter with a hairpin rope-barrier queue.
         GENERATED by tools/build_scene.py - edit that script, not this file.

         Every barrier, rope, counter panel, paint stripe and person is
         contype="0" conaffinity="0": kinematic scenery that cannot touch or
         push the robot.  The people are mocap bodies posed analytically each
         tick, so they add no degrees of freedom to the floating base and the
         walking policy sees exactly the robot it was trained on.  Following the
         bend and holding the lane are therefore properties of the CONTROLLER,
         graded by measured surface clearance, not by the contact solver. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.72 0.72 0.72" ambient="0.42 0.42 0.42" specular="0 0 0" />
        <rgba haze="0.19 0.21 0.25 1" />
        <global azimuth="140" elevation="-28" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.19 0.21 0.27" rgb2="0.04 0.05 0.07"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.29 0.29 0.32" rgb2="0.23 0.23 0.26" markrgb="0.40 0.40 0.44"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="16 16" reflectance="0.05" />
        <material name="hallmat" rgba="0.46 0.45 0.43 1" />
        <material name="lanemat" rgba="0.26 0.50 0.72 0.42" />
        <material name="lanecentremat" rgba="0.94 0.88 0.34 0.60" />
        <material name="postmat" rgba="0.62 0.63 0.66 1" />
        <material name="ropemat" rgba="0.74 0.20 0.20 1" />
        <material name="countermat" rgba="0.42 0.31 0.22 1" />
        <material name="countertopmat" rgba="0.80 0.78 0.72 1" />
        <material name="signmat" rgba="0.16 0.52 0.40 1" />
        <material name="wallmat" rgba="0.70 0.69 0.66 1" />
        <material name="shelfmat" rgba="0.52 0.47 0.42 1" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.11 0.14 0.22 1" />
        <material name="shoemat" rgba="0.05 0.05 0.06 1" />
        <material name="targetmat" rgba="0.20 0.92 0.46 0.55" />
        <material name="rejectmat" rgba="0.95 0.26 0.20 0.50" />
        <material name="tailmat" rgba="0.30 0.62 0.98 0.55" />
"""

FOOTER_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.0" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="queue_rig" mocap="true" pos="0 0 0.20">
            <camera name="queue_camera" fovy="58" />
        </body>
"""
