#!/usr/bin/env python3
"""Emit assets/scene_lead_me.xml — a concourse with sealed sides and three
destinations.

GENERATED from ``scripts/guide_layout.py`` and ``scripts/guide_cast.py`` rather
than hand-written, so the obstacles the planner searches against, the surfaces
the clearance gate grades, the bodies the camera ray-casts through and the
destinations a request resolves to are all the SAME objects.  A scene edit that
moves the partition moves it everywhere at once.

Everything except the robot is ``contype="0" conaffinity="0"``: kinematic
scenery that cannot touch or push the robot.  The adults are mocap bodies posed
analytically each tick, so they add no degrees of freedom to the floating base
and the walking policy sees exactly the robot it was trained on.  A step the
duck takes can therefore never be the result of somebody nudging it.

THE OBSTACLES BEING NON-COLLIDING IS DELIBERATE.  If they collided, "the route
avoided the partition" would be enforced by the contact solver rather than
demonstrated by the planner and the controller, and a duck that scraped along
the partition for five seconds would still pass.  With non-colliding scenery,
following a safe route is a property of the SOFTWARE, graded by measured surface
clearance every control tick.

PERSON GEOMETRY IS SCALED BY STATURE, so a shorter adult genuinely has a lower
head and the camera's topmost sample of them is genuinely nearer the ground.

THE THREE DESTINATION FIXTURES ARE REAL GEOMETRY, not HUD annotations.  Each is
a visible pylon at its own position with its own colour, so a viewer can see
that three candidates existed and which one the duck walked to.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from guide_cast import BASE_ORIGIN_Z, PEOPLE  # noqa: E402
from guide_layout import (  # noqa: E402
    DESTINATIONS,
    FLOOR_HALF,
    OBSTACLES,
    WALL_HALF_Z,
    WALL_T,
)
from guide_states import DUCK_START_XY, DUCK_START_YAW_DEG  # noqa: E402

HEADER = """<mujoco model="scene_lead_me">
    <!-- lead-me-somewhere: a concourse sealed on two sides, with three
         destinations one of which is requested at run time.
         GENERATED by tools/build_scene.py - edit that script, not this file.

         Every wall, partition, screen, column, crate, bench, planter, pylon and
         person is contype="0" conaffinity="0": kinematic scenery that cannot
         touch or push the robot.  Leading along a safe route is therefore a
         property of the PLANNER and the CONTROLLER, graded by measured surface
         clearance, not by the contact solver.

         partition_c is sealed against the north wall and hall_screen against
         the south wall, so no inflated path can pass either of them on the
         wrong side and the route has to zigzag.  Both are above 0.90 m and
         therefore occlude the head camera; the crates, bench and planter are
         below the lowest camera sample on a person and hide nobody. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.78 0.78 0.78" ambient="0.46 0.46 0.46" specular="0 0 0" />
        <rgba haze="0.18 0.20 0.25 1" />
        <global azimuth="150" elevation="-30" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.17 0.19 0.25" rgb2="0.04 0.05 0.08"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.28 0.28 0.31" rgb2="0.23 0.23 0.26" markrgb="0.38 0.38 0.42"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="20 20" reflectance="0.05" />
        <material name="hallmat" rgba="0.47 0.46 0.44 1" />
        <material name="wallmat" rgba="0.69 0.68 0.65 1" />
        <material name="partitionmat" rgba="0.34 0.37 0.45 1" />
        <material name="screenmat" rgba="0.30 0.40 0.44 1" />
        <material name="columnmat" rgba="0.72 0.71 0.68 1" />
        <material name="cratemat" rgba="0.50 0.38 0.24 1" />
        <material name="benchmat" rgba="0.44 0.33 0.24 1" />
        <material name="plantermat" rgba="0.37 0.29 0.21 1" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.12 0.15 0.22 1" />
        <material name="shoemat" rgba="0.05 0.05 0.06 1" />
        <material name="routemat" rgba="0.36 0.78 0.98 0.45" />
        <material name="wpmat" rgba="0.98 0.80 0.24 0.60" />
        <material name="goalmat" rgba="0.24 0.94 0.52 0.55" />
        <material name="waitmat" rgba="0.98 0.42 0.30 0.55" />
        <material name="trailmat" rgba="0.62 0.52 0.95 0.32" />
        <material name="arrivemat" rgba="0.20 0.98 0.60 0.70" />
"""

WORLD_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.6" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="guide_rig" mocap="true" pos="0 0 0.20">
            <camera name="guide_camera" fovy="58" />
        </body>
"""

# How many world-space markers the scene carries.
ROUTE_DISCS = 26
WAYPOINT_DISCS = 8
TRAIL_DISCS = 14


def _box(name, pos, size, material) -> str:
    return (
        f'        <geom name="{name}" type="box" pos="{pos[0]:.4f} {pos[1]:.4f} '
        f'{pos[2]:.4f}" size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def _cylinder(name, pos, radius, half_h, material) -> str:
    return (
        f'        <geom name="{name}" type="cylinder" pos="{pos[0]:.4f} '
        f'{pos[1]:.4f} {pos[2]:.4f}" size="{radius:.4f} {half_h:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def hall() -> str:
    """Concourse floor slab and the four perimeter walls."""
    parts = ["\n        <!-- concourse floor and perimeter walls -->\n"]
    parts.append(_box("hall_floor", (0.0, 0.0, 0.0015),
                      (FLOOR_HALF[0], FLOOR_HALF[1], 0.0015), "hallmat"))
    for tag, sign in (("e", +1.0), ("w", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (sign * (FLOOR_HALF[0] + WALL_T), 0.0, WALL_HALF_Z),
            (WALL_T, FLOOR_HALF[1] + 2 * WALL_T, WALL_HALF_Z), "wallmat"))
    for tag, sign in (("n", +1.0), ("s", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (0.0, sign * (FLOOR_HALF[1] + WALL_T), WALL_HALF_Z),
            (FLOOR_HALF[0] + 2 * WALL_T, WALL_T, WALL_HALF_Z), "wallmat"))
    return "".join(parts)


def furniture() -> str:
    """Every obstacle in :data:`guide_layout.OBSTACLES`, at its height.

    Geom names are ``obs_<name>`` so ``rollout_guide.scenery_geom_names`` can
    collect them from the model rather than from a hand-kept list.
    """
    material = {"partition_c": "partitionmat", "hall_screen": "screenmat",
                "column_e": "columnmat", "column_w": "columnmat",
                "crate_ne": "cratemat", "bench_s": "benchmat",
                "planter_w": "plantermat"}
    parts = ["\n        <!-- route-shaping bodies -->\n"]
    for obstacle in OBSTACLES:
        half_h = 0.5 * obstacle.height_m
        center = (obstacle.center[0], obstacle.center[1], half_h)
        if obstacle.kind == "circle":
            parts.append(_cylinder(f"obs_{obstacle.name}", center,
                                   obstacle.radius, half_h,
                                   material[obstacle.name]))
        else:
            parts.append(_box(f"obs_{obstacle.name}", center,
                              (obstacle.half[0], obstacle.half[1], half_h),
                              material[obstacle.name]))
    return "".join(parts)


def destinations() -> str:
    """The three candidate destinations, as visible coloured pylons.

    Real geometry rather than HUD annotation: a viewer can see that three places
    existed and which one the duck walked to.  Named ``dest_<KEY>`` and given
    their own material so the HUD legend and the picture use the same colour.
    """
    parts = ["\n        <!-- the three candidate destinations -->\n"]
    for destination in DESTINATIONS:
        key = destination.key.lower()
        x, y = destination.xy
        parts.append(_box(f"dest_{key}_base", (x, y, 0.030),
                          (0.30, 0.30, 0.030), f"dest_{key}_mat"))
        parts.append(_cylinder(f"dest_{key}_post", (x, y, 0.52), 0.055, 0.49,
                               f"dest_{key}_mat"))
        parts.append(_box(f"dest_{key}_sign", (x, y, 1.12),
                          (0.055, 0.30, 0.20), f"dest_{key}_mat"))
    return "".join(parts)


def markers() -> str:
    """Mocap discs: the planned route, its waypoints, the goal, the wait spot."""
    entries = [(f"route_{i}", "routemat", 0.036, 0.004)
               for i in range(ROUTE_DISCS)]
    entries += [(f"wp_{i}", "wpmat", 0.062, 0.006) for i in range(WAYPOINT_DISCS)]
    entries += [(f"trail_{i}", "trailmat", 0.038, 0.004)
                for i in range(TRAIL_DISCS)]
    entries += [("goal_marker", "goalmat", 0.130, 0.007),
                ("wait_marker", "waitmat", 0.115, 0.007),
                ("arrive_marker", "arrivemat", 0.165, 0.009)]
    parts = ["\n        <!-- route and decision markers: mocap discs -->\n"]
    for name, material, radius, half_h in entries:
        parts.append(
            f'        <body name="{name}" mocap="true" pos="0 0 -3.0">\n'
            f'            <geom name="{name}_disc" type="cylinder"'
            f' size="{radius:.3f} {half_h:.3f}" material="{material}"'
            f' contype="0" conaffinity="0" />\n'
            f"        </body>\n"
        )
    return "".join(parts)


def person_block(person) -> str:
    """One adult, SCALED BY STATURE so height is geometry, not a label."""
    s = person.stature
    name = person.name
    lines = [
        f'        <body name="person_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_torso" type="capsule"'
        f' fromto="0 0 {-0.10 * s:.4f} 0 0 {0.16 * s:.4f}"'
        f' size="{0.078 * s:.4f}" material="{name}_shirt"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere"'
        f' pos="0 0 {0.255 * s:.4f}" size="{0.064 * s:.4f}" material="skinmat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere"'
        f' pos="{0.060 * s:.4f} 0 {0.252 * s:.4f}" size="{0.019 * s:.4f}"'
        f' material="{name}_shirt" contype="0" conaffinity="0" />',
    ]
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}"'
            f' pos="0 {sy * s:+.4f} {-0.10 * s:.4f}">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.26 * s:.4f}"'
            f' size="{0.033 * s:.4f}" material="trousermat"'
            f' contype="0" conaffinity="0" />'
            f'<geom type="capsule"'
            f' fromto="0 0 {-0.26 * s:.4f} {0.072 * s:.4f} 0 {-0.272 * s:.4f}"'
            f' size="{0.035 * s:.4f}" material="shoemat"'
            f' contype="0" conaffinity="0" /></body>')
    for side, sy in (("l", 0.078), ("r", -0.078)):
        lines.append(
            f'            <body name="{name}_arm_{side}"'
            f' pos="0 {sy * s:+.4f} {0.115 * s:.4f}">'
            f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.205 * s:.4f}"'
            f' size="{0.026 * s:.4f}" material="skinmat"'
            f' contype="0" conaffinity="0" /></body>')
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    materials = "".join(
        f'        <material name="{p.name}_shirt" rgba="{p.rgba}" />\n'
        for p in PEOPLE)
    materials += "".join(
        f'        <material name="dest_{d.key.lower()}_mat" rgba="{d.rgba}" />\n'
        for d in DESTINATIONS)
    parts = [HEADER + materials + WORLD_OPEN,
             hall(), furniture(), destinations(), markers(),
             "\n        <!-- adults: mocap, non-colliding -->\n"]
    parts.extend(person_block(p) for p in PEOPLE)
    parts.append("    </worldbody>\n\n")

    yaw = math.radians(DUCK_START_YAW_DEG)
    quat = (math.cos(0.5 * yaw), 0.0, 0.0, math.sin(0.5 * yaw))
    base = (f"{DUCK_START_XY[0]:.4f} {DUCK_START_XY[1]:.4f} 0.12 "
            f"{quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f} {quat[3]:.6f}")
    hinge_pad = " ".join(["0"] * (4 * len(PEOPLE)))
    stand = (
        f"        {base}\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 4 * len(PEOPLE)))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="{base} {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = (Path(__file__).resolve().parents[1] / "assets"
           / "scene_lead_me.xml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  people={len(PEOPLE)}  obstacles={len(OBSTACLES)}  "
          f"destinations={len(DESTINATIONS)}  base_origin_z={BASE_ORIGIN_Z}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
