#!/usr/bin/env python3
"""Emit assets/scene_come_here_recall.xml.

Five visually distinct adults stand around a child-sized Microduck.  One of
them at a time calls the duck over; the duck searches, locks the caller,
walks to a safe standoff and stops facing them.

Every adult and every marker is a MOCAP body with ``contype="0"
conaffinity="0"``: kinematically scripted, never dynamically simulated, and
physically unable to touch or push the robot.  They add no degrees of freedom
to the floating base, so the walking policy sees exactly the robot it was
trained on.

Each adult has two hinged legs and two hinged arms.  The arm hinge range
reaches past vertical (``-190 deg``) so the ACTIVE CALLER can raise one arm
overhead and wave it, which is what makes the caller unmistakable in the wide
shot without relying on the HUD.

Generated rather than hand-written so the five bodies stay consistent and the
keyframe padding (4 hinges per adult) is computed instead of guessed.
"""

from __future__ import annotations

from pathlib import Path

# name, shirt rgba, cap rgba.  Shirt AND cap carry the identity, so an adult
# stays recognisable from behind and at the small PiP resolution.
ADULTS: tuple[tuple[str, str, str], ...] = (
    ("blue", "0.10 0.32 0.94 1", "0.05 0.18 0.62 1"),
    ("green", "0.10 0.72 0.28 1", "0.04 0.42 0.16 1"),
    ("red", "0.90 0.12 0.14 1", "0.55 0.05 0.07 1"),
    ("yellow", "0.96 0.74 0.10 1", "0.70 0.48 0.04 1"),
    ("purple", "0.64 0.20 0.90 1", "0.36 0.08 0.55 1"),
)

# name, "radius half-height", material, z
MARKERS: tuple[tuple[str, str, str, str], ...] = (
    ("call_ring", "0.150 0.004", "callringmat", "0.008"),
    ("goal_marker", "0.052 0.004", "goalmat", "0.011"),
)

HEADER = """<mujoco model="scene_come_here_recall">
    <!-- come-here-recall: five adults around a child-sized Microduck; one of
         them calls the duck over at a time.  GENERATED by tools/build_scene.py
         - edit that script, not this file.

         Every adult and every marker is a mocap body with contype="0"
         conaffinity="0": kinematically scripted, never dynamically simulated,
         and physically unable to touch or push the robot.  They add no degrees
         of freedom to the floating base, so the walking policy sees exactly the
         robot it was trained on. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.64 0.64 0.64" ambient="0.33 0.33 0.33" specular="0 0 0" />
        <rgba haze="0.15 0.25 0.35 1" />
        <global azimuth="160" elevation="-20" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.30 0.50 0.70" rgb2="0 0 0"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.20 0.30 0.40" rgb2="0.10 0.20 0.30" markrgb="0.8 0.8 0.8"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="5 5" reflectance="0.2" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.08 0.12 0.22 1" />
        <material name="shoemat" rgba="0.04 0.04 0.05 1" />
        <material name="callringmat" rgba="1.0 0.86 0.20 0.55" />
        <material name="goalmat" rgba="0.25 1.0 0.55 0.80" />
        <material name="beaconmat" rgba="1.0 0.88 0.25 0.90" />
"""

FOOTER_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.6" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the attention camera used both for the
             PiP and for every visibility measurement, oriented with world up. -->
        <body name="attention_rig" mocap="true" pos="0 0 0.20">
            <camera name="attention_camera" fovy="58" />
        </body>

        <!-- Floating beacon parked over whoever is calling right now. -->
        <body name="call_beacon" mocap="true" pos="0 0 -0.30">
            <geom name="call_beacon_cone" type="cylinder" size="0.045 0.055"
                  material="beaconmat" contype="0" conaffinity="0" />
        </body>
"""


def adult_block(name: str, x: float, y: float) -> str:
    """One adult: torso, head, cap, two hinged legs, two hinged arms."""
    shirt = f"{name}_shirt"
    cap = f"{name}_cap"
    lines = [
        f'        <body name="person_{name}" mocap="true" pos="{x:.2f} {y:.2f} 0.36">',
        f'            <geom name="{name}_torso" type="capsule" fromto="0 0 -0.10 0 0 0.16"'
        f' size="0.078" material="{shirt}" contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere" pos="0 0 0.255" size="0.064"'
        f' material="skinmat" contype="0" conaffinity="0" />',
        # Cap: identity colour visible from every angle, including from above.
        f'            <geom name="{name}_cap" type="ellipsoid" pos="0 0 0.300"'
        f' size="0.066 0.066 0.034" material="{cap}" contype="0" conaffinity="0" />',
        f'            <geom name="{name}_brim" type="box" pos="0.062 0 0.286"'
        f' size="0.038 0.058 0.006" material="{cap}" contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere" pos="0.060 0 0.250" size="0.019"'
        f' material="{shirt}" contype="0" conaffinity="0" />',
    ]
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}" pos="0 {sy:+.3f} -0.10">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0" range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 -0.26" size="0.033"'
            f' material="trousermat" contype="0" conaffinity="0" />'
            f'<geom type="capsule" fromto="0 0 -0.26 0.072 0 -0.272" size="0.035"'
            f' material="shoemat" contype="0" conaffinity="0" /></body>'
        )
    # Arms reach past vertical so the caller can raise one overhead and wave it.
    # Hinge about +y: angle 0 hangs down, -180 deg points straight up.
    for side, sy in (("l", 0.078), ("r", -0.078)):
        lines.append(
            f'            <body name="{name}_arm_{side}" pos="0 {sy:+.3f} 0.115">'
            f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
            f' range="-195 45" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 -0.205" size="0.026"'
            f' material="skinmat" contype="0" conaffinity="0" />'
            f'<geom type="sphere" pos="0 0 -0.222" size="0.030"'
            f' material="{shirt}" contype="0" conaffinity="0" /></body>'
        )
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    parts = [HEADER]
    for name, shirt, cap in ADULTS:
        parts.append(f'        <material name="{name}_shirt" rgba="{shirt}" />\n')
        parts.append(f'        <material name="{name}_cap" rgba="{cap}" />\n')
    parts.append(FOOTER_OPEN)
    for mname, size, mat, z in MARKERS:
        parts.append(
            f'        <body name="{mname}" mocap="true" pos="0 0 {z}">\n'
            f'            <geom name="{mname}_disc" type="cylinder" size="{size}"'
            f' material="{mat}" contype="0" conaffinity="0" />\n'
            f"        </body>\n"
        )
    # Spread the initial poses; people_routes.py overrides them at t=0.
    ring = ((1.9, 0.0), (1.1, 1.6), (-1.4, 1.3), (-1.9, -0.6), (0.4, -1.9))
    for (name, _, _), (x, y) in zip(ADULTS, ring):
        parts.append(adult_block(name, x, y))
    parts.append("    </worldbody>\n\n")

    # 7 free-joint qpos + 14 actuated joints + 4 hinges per adult.
    hinge_pad = " ".join(["0"] * (4 * len(ADULTS)))
    stand = (
        "        0 0 0.12 1 0 0 0\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 4 * len(ADULTS)))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="0 0 0.12 1 0 0 0 {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = Path(__file__).resolve().parents[1] / "assets" / "scene_come_here_recall.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
