#!/usr/bin/env python3
"""Emit assets/scene_gesture.xml - an open training area with five adults whose
arms are REAL articulated chains.

GENERATED from ``scripts/gest_arena.py`` and ``scripts/gest_cast.py`` rather
than hand-written, so the surfaces the clearance gate grades, the fixtures the
routes are solved against, the bodies the choreography poses and the geometry
the camera ray-casts through are all the SAME objects.  Moving a rack moves it
everywhere at once.

THE ARMS ARE THE POINT OF THIS FILE
-------------------------------------
Each person carries two three-link arm chains: shoulder (hinge about the
person's y, flexion) -> upper arm (hinge about x, abduction) -> forearm (hinge
about y, elbow).  Every link is a real body with a real geom, so:

* the WORLD POSITIONS of the shoulder, elbow and hand are computed by MuJoCo
  from real joint angles, and those are the positions :mod:`gest_pose` measures;
* the camera's occlusion ray cast strikes the actual arm geometry, so "the duck
  could see the arm" is a statement about optics;
* a raised arm genuinely changes the body's silhouette, which is why the
  visibility samples include hand-height points rather than only the torso.

An arm drawn as a decoration, or written as a geom offset, would break all
three at once.

Everything except the robot is ``contype="0" conaffinity="0"``: kinematic
scenery that cannot touch or push the robot.  Staying clear of five adults in an
open area is therefore a property of the SOFTWARE, graded by measured surface
clearance every control tick, rather than something the contact solver enforced.

THE TWO MARKS ARE PAINTED ON THE FLOOR, because both are places the behavior
makes claims about: a viewer must be able to see the instructor standing on hers
for the whole session, and see where the duck started from.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from gest_arena import (  # noqa: E402
    DUCK_START,
    DUCK_START_YAW_DEG,
    FIXTURES,
    FLOOR_HALF,
    INSTRUCTOR_MARK,
    MARK_HALF,
    WALL_HALF_Z,
    WALL_T,
)
from gest_cast import (  # noqa: E402
    FOREARM_L,
    HAND_R,
    PEOPLE,
    SHOULDER_DY,
    SHOULDER_DZ,
    UPPER_ARM_L,
)

HEADER = """<mujoco model="scene_gesture">
    <!-- gesture-response: an open training area, one instructor on a painted
         mark, four distracting adults, and five people whose ARMS ARE REAL
         ARTICULATED CHAINS driven through real hinge joints.
         GENERATED by tools/build_scene.py - edit that script, not this file.

         Every wall, rack, cone, bench, post, mark and person is contype="0"
         conaffinity="0": kinematic scenery that cannot touch or push the
         robot.  Reading a gesture, executing it, and keeping clear of five
         adults are therefore properties of the SOFTWARE, graded by measured
         surface clearance and by where the trunk actually went, not by the
         contact solver. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.82 0.82 0.82" ambient="0.48 0.48 0.48" specular="0 0 0" />
        <rgba haze="0.18 0.20 0.25 1" />
        <global azimuth="150" elevation="-30" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.17 0.19 0.25" rgb2="0.04 0.05 0.09"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.28 0.28 0.31" rgb2="0.23 0.23 0.26" markrgb="0.38 0.38 0.42"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="20 20" reflectance="0.05" />
        <material name="hallmat" rgba="0.40 0.43 0.44 1" />
        <material name="wallmat" rgba="0.66 0.66 0.63 1" />
        <material name="rackmat" rgba="0.42 0.39 0.35 1" />
        <material name="benchmat" rgba="0.46 0.36 0.24 1" />
        <material name="columnmat" rgba="0.58 0.58 0.60 1" />
        <material name="conemat" rgba="0.98 0.52 0.12 1" />
        <material name="markmat" rgba="0.98 0.78 0.22 0.42" />
        <material name="startmat" rgba="0.44 0.62 0.98 0.38" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="palmmat" rgba="0.93 0.78 0.66 1" />
        <material name="trousermat" rgba="0.12 0.15 0.22 1" />
        <material name="shoemat" rgba="0.05 0.05 0.06 1" />
        <material name="headingmat" rgba="0.44 0.86 0.98 0.55" />
        <material name="commandmat" rgba="0.98 0.36 0.42 0.50" />
        <material name="trailmat" rgba="0.62 0.52 0.95 0.32" />
        <material name="targetmat" rgba="0.98 0.24 0.30 0.55" />
        <material name="focusmat" rgba="0.30 0.94 0.60 0.45" />
"""

WORLD_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.8" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="gesture_rig" mocap="true" pos="0 0 0.20">
            <camera name="gesture_camera" fovy="58" />
        </body>
"""

TRAIL_DISCS = 18
HEADING_DISCS = 8


def _box(name, pos, size, material) -> str:
    return (
        f'        <geom name="{name}" type="box" pos="{pos[0]:.4f} {pos[1]:.4f} '
        f'{pos[2]:.4f}" size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def _cyl(name, pos, radius, half_h, material) -> str:
    return (
        f'        <geom name="{name}" type="cylinder" pos="{pos[0]:.4f} '
        f'{pos[1]:.4f} {pos[2]:.4f}" size="{radius:.4f} {half_h:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def hall() -> str:
    """Training-area floor slab and the four perimeter walls."""
    parts = ["\n        <!-- training area floor and perimeter walls -->\n"]
    parts.append(_box("hall_floor", (0.0, 0.0, 0.0015),
                      (FLOOR_HALF[0], FLOOR_HALF[1], 0.0015), "hallmat"))
    for tag, sign in (("e", +1.0), ("w", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (sign * (FLOOR_HALF[0] + WALL_T), 0.0, WALL_HALF_Z),
            (WALL_T, FLOOR_HALF[1] + 2 * WALL_T, WALL_HALF_Z), "wallmat"))
    for tag, sign in (("n", +1.0), ("s", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (0.0, sign * (FLOOR_HALF[1] + WALL_T), WALL_HALF_Z),
            (FLOOR_HALF[0] + 2 * WALL_T, WALL_T, WALL_HALF_Z), "wallmat"))
    return "".join(parts)


def fixtures() -> str:
    """Every static fixture in :data:`gest_arena.FIXTURES`.

    Geom names come from the fixture's own name, so
    ``rollout_gesture.scenery_geom_names`` collects them from the model rather
    than from a hand-kept list and a new fixture cannot silently escape the
    clearance gate.
    """
    parts = ["\n        <!-- racks, posts, cones and the spectator bench -->\n"]
    for fixture in FIXTURES:
        half_h = 0.5 * fixture.height_m
        if fixture.kind == "cylinder":
            parts.append(_cyl(
                fixture.name,
                (fixture.center[0], fixture.center[1], half_h),
                fixture.radius, half_h, fixture.material))
        else:
            parts.append(_box(
                fixture.name,
                (fixture.center[0], fixture.center[1], half_h),
                (fixture.half[0], fixture.half[1], half_h),
                fixture.material))
    return "".join(parts)


def marks() -> str:
    """The instructor's painted mark and the duck's start pad."""
    parts = ["\n        <!-- the two painted marks -->\n"]
    parts.append(_box("instructor_mark",
                      (INSTRUCTOR_MARK[0], INSTRUCTOR_MARK[1], 0.005),
                      (MARK_HALF[0], MARK_HALF[1], 0.005), "markmat"))
    parts.append(_box("start_pad", (DUCK_START[0], DUCK_START[1], 0.005),
                      (MARK_HALF[0], MARK_HALF[1], 0.005), "startmat"))
    return "".join(parts)


def markers() -> str:
    """Mocap discs: the duck's trail, its commanded heading, its goal."""
    entries = [(f"trail_{i}", "trailmat", 0.032, 0.004)
               for i in range(TRAIL_DISCS)]
    entries += [(f"heading_{i}", "headingmat", 0.028, 0.004)
                for i in range(HEADING_DISCS)]
    entries += [("target_marker", "targetmat", 0.090, 0.006)]
    entries += [("focus_marker", "focusmat", 0.120, 0.007)]
    parts = ["\n        <!-- trail, heading and focus markers -->\n"]
    for name, material, radius, half_h in entries:
        parts.append(
            f'        <body name="{name}" mocap="true" pos="0 0 -3.0">\n'
            f'            <geom name="{name}_disc" type="cylinder"'
            f' size="{radius:.3f} {half_h:.3f}" material="{material}"'
            f' contype="0" conaffinity="0" />\n'
            f"        </body>\n")
    return "".join(parts)


def arm_chain(name: str, side: str, stature: float) -> list[str]:
    """One arm: three nested bodies, three hinge joints, real geometry.

    The nesting order fixes the rotation convention the whole behavior is
    written against, and it is stated once in ``gest_arm``:

        shoulder (hinge y, flexion) -> upper arm (hinge x, abduction)
                                    -> forearm (hinge y, elbow)

    The joint RANGES are deliberately wide.  They exist to keep the chain
    physically sane, not to encode the gestures: a template that needed a joint
    outside its range would silently clamp and produce a pose the classifier had
    never been tuned on, so ``tools/check_gestures.py`` measures every template
    on the compiled model and would show the clamp as a feature outside its
    window.
    """
    s = stature
    sy = SHOULDER_DY * s if side == "l" else -SHOULDER_DY * s
    upper = UPPER_ARM_L * s
    fore = FOREARM_L * s
    hand_r = HAND_R * s
    # The open palm is a flattened box on the LEFT/RIGHT hand, oriented across
    # the forearm, so a raised straight arm reads as an open palm in the PiP
    # rather than as a stick.
    return [
        f'            <body name="{name}_shoulder_{side}"'
        f' pos="0 {sy:+.4f} {SHOULDER_DZ * s:.4f}">',
        # The shoulder pivot carries a joint but no geom, and MuJoCo refuses a
        # moving body with no mass.  An explicit token inertial keeps the pivot
        # a real body - which is what makes its WORLD POSITION the shoulder
        # keypoint ``gest_pose`` measures - without adding a visible link.
        f'                <inertial pos="0 0 0" mass="0.01"'
        f' diaginertia="1e-5 1e-5 1e-5" />',
        f'                <joint name="{name}_{side}_flex" type="hinge"'
        f' axis="0 1 0" range="-180 60" damping="1" />',
        f'                <body name="{name}_upper_{side}" pos="0 0 0">',
        f'                    <joint name="{name}_{side}_abd" type="hinge"'
        f' axis="1 0 0" range="-120 120" damping="1" />',
        f'                    <geom name="{name}_upper_{side}_g" type="capsule"'
        f' fromto="0 0 0 0 0 {-upper:.4f}" size="{0.026 * s:.4f}"'
        f' material="skinmat" contype="0" conaffinity="0" />',
        f'                    <body name="{name}_fore_{side}"'
        f' pos="0 0 {-upper:.4f}">',
        f'                        <joint name="{name}_{side}_elbow"'
        f' type="hinge" axis="0 1 0" range="-150 10" damping="1" />',
        f'                        <geom name="{name}_fore_{side}_g"'
        f' type="capsule" fromto="0 0 0 0 0 {-fore:.4f}"'
        f' size="{0.023 * s:.4f}" material="skinmat"'
        f' contype="0" conaffinity="0" />',
        # The HAND body.  Its world position is what ``gest_pose`` measures, so
        # it is a real body rather than a geom on the forearm.
        f'                        <body name="{name}_hand_{side}"'
        f' pos="0 0 {-fore:.4f}">',
        f'                            <geom name="{name}_palm_{side}"'
        f' type="box" size="{hand_r:.4f} {0.014 * s:.4f} {hand_r * 1.15:.4f}"'
        f' material="palmmat" contype="0" conaffinity="0" />',
        f'                        </body>',
        f'                    </body>',
        f'                </body>',
        f'            </body>',
    ]


def person_block(person) -> str:
    """One person, SCALED BY STATURE, with swinging legs and real arms."""
    s = person.stature
    name = person.name
    lines = [
        f'        <body name="actor_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_torso" type="capsule"'
        f' fromto="0 0 {-0.10 * s:.4f} 0 0 {0.17 * s:.4f}"'
        f' size="{0.079 * s:.4f}" material="{name}_shirt"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere"'
        f' pos="0 0 {0.262 * s:.4f}" size="{0.064 * s:.4f}" material="skinmat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere"'
        f' pos="{0.060 * s:.4f} 0 {0.259 * s:.4f}" size="{0.019 * s:.4f}"'
        f' material="{name}_shirt" contype="0" conaffinity="0" />',
    ]
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}"'
            f' pos="0 {sy * s:+.4f} {-0.10 * s:.4f}">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.26 * s:.4f}"'
            f' size="{0.033 * s:.4f}" material="trousermat"'
            f' contype="0" conaffinity="0" />'
            f'<geom type="capsule"'
            f' fromto="0 0 {-0.26 * s:.4f} {0.072 * s:.4f} 0 {-0.272 * s:.4f}"'
            f' size="{0.035 * s:.4f}" material="shoemat"'
            f' contype="0" conaffinity="0" /></body>')
    for side in ("l", "r"):
        lines.extend(arm_chain(name, side, s))
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    materials = "".join(
        f'        <material name="{p.name}_shirt" rgba="{p.rgba}" />\n'
        for p in PEOPLE)
    parts = [HEADER + materials + WORLD_OPEN,
             hall(), fixtures(), marks(), markers(),
             "\n        <!-- the people: mocap bases, real articulated arms -->\n"]
    for person in PEOPLE:
        parts.append(person_block(person))
    parts.append("    </worldbody>\n\n")

    yaw = math.radians(DUCK_START_YAW_DEG)
    quat = (math.cos(0.5 * yaw), 0.0, 0.0, math.sin(0.5 * yaw))
    base = (f"{DUCK_START[0]:.4f} {DUCK_START[1]:.4f} 0.12 "
            f"{quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f} {quat[3]:.6f}")
    # Two leg hinges plus six arm hinges per person.
    hinge_pad = " ".join(["0"] * (8 * len(PEOPLE)))
    stand = (
        f"        {base}\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 8 * len(PEOPLE)))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="{base} {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = (Path(__file__).resolve().parents[1] / "assets" / "scene_gesture.xml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  people={len(PEOPLE)}  fixtures={len(FIXTURES)}  "
          f"instructor_mark={INSTRUCTOR_MARK}  duck_start={DUCK_START}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
