#!/usr/bin/env python3
"""Emit assets/scene_crosswalk_guardian.xml.

An UNSIGNALLED two-lane street with a marked zebra crossing, a dropped kerb,
painted wait lines on both sides and a green "safe zone" on the far pavement.
Six road users drive along the two lanes on continuous scripted trajectories.

Layout, in world coordinates (the duck crosses along +X, traffic runs along Y):

    x = -2.05   duck start, near pavement
    x = -0.78   near WAIT LINE (painted)
    x = -0.55   near road edge  ────────────┐
    x = -0.275  NEAR LANE centre, traffic −Y │  road, 1.10 m wide
    x = +0.275  FAR  LANE centre, traffic +Y │
    x = +0.55   far road edge   ────────────┘
    x = +0.78   far wait line
    x = +1.075  SAFE ZONE centre, far pavement

Traffic sides follow right-hand driving, so the NEAR lane carries vehicles
coming from the duck's LEFT (+Y) and the FAR lane vehicles coming from its
RIGHT (−Y).  That is what makes LOOK_LEFT → LOOK_RIGHT → LOOK_LEFT_AGAIN the
correct order rather than a decorative one.

Every vehicle, every marker and every piece of street furniture is
``contype="0" conaffinity="0"``.  Vehicles are MOCAP bodies posed analytically
each tick: kinematically scripted, never dynamically simulated, and physically
unable to touch or push the robot.  They add no degrees of freedom to the
floating base, so the walking policy sees exactly the robot it was trained on.
A crossing therefore cannot succeed by a vehicle nudging the duck across.

Generated rather than hand-written so the six vehicles, the zebra bars and the
lane dashes stay consistent and the keyframe padding is computed, not guessed.
"""

from __future__ import annotations

from pathlib import Path

# --- street geometry (metres) ------------------------------------------------
ROAD_HALF_WIDTH = 0.55          # road spans x in [-0.55, +0.55]
ROAD_HALF_LENGTH = 46.0         # exceeds traffic.LOOP_HALF_Y, so no vehicle
                                # is ever posed off the asphalt
LANE_OFFSET = 0.275             # lane centres at x = -/+0.275
CROSSWALK_HALF_SPAN = 0.55      # zebra bars span y in [-0.55, +0.55]
KERB_X = 0.61
WAIT_LINE_X = 0.78
PAVEMENT_OUTER = 2.60
SAFE_ZONE_X = 1.075
SAFE_ZONE_HALF = 0.275

# Zebra bars: long across the road (the pedestrian's direction of travel),
# narrow along it, repeating down the road axis.
ZEBRA_BARS = 7
ZEBRA_HALF_Y = 0.055
ZEBRA_PITCH = 0.170

# name, kind, body rgba, trim rgba
VEHICLES: tuple[tuple[str, str, str, str], ...] = (
    ("hatch", "car", "0.88 0.16 0.14 1", "0.30 0.03 0.04 1"),
    ("sedan", "car", "0.12 0.34 0.86 1", "0.04 0.10 0.32 1"),
    ("scooter", "two_wheeler", "0.10 0.78 0.72 1", "0.05 0.28 0.28 1"),
    ("van", "car", "0.92 0.92 0.95 1", "0.35 0.36 0.40 1"),
    ("bike", "two_wheeler", "0.20 0.80 0.28 1", "0.05 0.30 0.10 1"),
    ("taxi", "car", "0.98 0.76 0.06 1", "0.36 0.26 0.02 1"),
    ("courier", "car", "0.62 0.26 0.86 1", "0.26 0.08 0.38 1"),
)

# Poles marking the two road sectors the duck has to check.  They are visual
# anchors only: sector visibility is measured against lane sample points
# through the real camera frustum, not against these geoms.
SECTOR_POLES: tuple[tuple[str, float, float, str], ...] = (
    ("left_sector_pole", -0.70, 2.30, "leftsectormat"),
    ("right_sector_pole", 0.70, -2.30, "rightsectormat"),
)

HEADER = """<mujoco model="scene_crosswalk_guardian">
    <!-- crosswalk-guardian: an unsignalled two-lane street with a marked zebra
         crossing.  GENERATED by tools/build_scene.py - edit that script, not
         this file.

         Every vehicle and every marker is a mocap body with contype="0"
         conaffinity="0": kinematically scripted, never dynamically simulated,
         and physically unable to touch or push the robot.  They add no degrees
         of freedom to the floating base, so the walking policy sees exactly the
         robot it was trained on, and a completed crossing can never be the
         result of a vehicle pushing the duck. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.68 0.68 0.68" ambient="0.34 0.34 0.34" specular="0 0 0" />
        <rgba haze="0.16 0.24 0.32 1" />
        <global azimuth="150" elevation="-22" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.36 0.52 0.72" rgb2="0.05 0.08 0.14"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.16 0.30 0.18" rgb2="0.11 0.23 0.13" markrgb="0.32 0.46 0.34"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="6 6" reflectance="0.05" />
        <material name="asphaltmat" rgba="0.135 0.140 0.155 1" />
        <material name="pavementmat" rgba="0.62 0.62 0.60 1" />
        <material name="kerbmat" rgba="0.78 0.78 0.75 1" />
        <material name="zebramat" rgba="0.95 0.95 0.93 1" />
        <material name="dashmat" rgba="0.90 0.88 0.55 1" />
        <material name="waitlinemat" rgba="0.98 0.82 0.12 1" />
        <material name="safezonemat" rgba="0.20 0.95 0.45 0.42" />
        <material name="glassmat" rgba="0.30 0.44 0.52 1" />
        <material name="tyremat" rgba="0.07 0.07 0.08 1" />
        <material name="ridermat" rgba="0.94 0.36 0.10 1" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="polemat" rgba="0.45 0.47 0.50 1" />
        <material name="leftsectormat" rgba="1.0 0.55 0.10 1" />
        <material name="rightsectormat" rgba="0.35 0.65 1.0 1" />
        <material name="buildingmat" rgba="0.42 0.40 0.44 1" />
        <material name="roofmat" rgba="0.26 0.24 0.28 1" />
        <material name="trunkmat" rgba="0.32 0.22 0.14 1" />
        <material name="foliagemat" rgba="0.14 0.44 0.20 1" />
    </asset>

    <worldbody>
        <light pos="0 0 4.2" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="guardian_rig" mocap="true" pos="0 0 0.20">
            <camera name="guardian_camera" fovy="58" />
        </body>
"""


def _box(name: str, pos: tuple[float, float, float],
         size: tuple[float, float, float], material: str) -> str:
    return (
        f'        <geom name="{name}" type="box" pos="{pos[0]:.4f} {pos[1]:.4f} '
        f'{pos[2]:.4f}" size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}" '
        f'material="{material}" contype="0" conaffinity="0" />\n'
    )


def street() -> str:
    """Road surface, pavements, dropped kerbs, zebra, dashes and wait lines."""
    parts = ["\n        <!-- road surface and pavements -->\n"]
    parts.append(_box("road", (0.0, 0.0, 0.0015),
                      (ROAD_HALF_WIDTH, ROAD_HALF_LENGTH, 0.0015), "asphaltmat"))
    half_pavement = 0.5 * (PAVEMENT_OUTER - KERB_X)
    for side, sign in (("near", -1.0), ("far", 1.0)):
        parts.append(_box(
            f"pavement_{side}",
            (sign * (KERB_X + half_pavement), 0.0, 0.0020),
            (half_pavement, ROAD_HALF_LENGTH, 0.0020), "pavementmat"))
    # Dropped kerb: the kerb stops either side of the crossing, so the duck
    # walks onto a flush ramp instead of stepping over an edge.
    parts.append("\n        <!-- kerbs, dropped at the crossing -->\n")
    kerb_len = 0.5 * (ROAD_HALF_LENGTH - CROSSWALK_HALF_SPAN - 0.08)
    kerb_mid = CROSSWALK_HALF_SPAN + 0.08 + kerb_len
    for side, sx in (("near", -1.0), ("far", 1.0)):
        for end, sy in (("plus", 1.0), ("minus", -1.0)):
            parts.append(_box(
                f"kerb_{side}_{end}",
                (sx * KERB_X, sy * kerb_mid, 0.0140),
                (0.030, kerb_len, 0.0140), "kerbmat"))
    parts.append("\n        <!-- zebra crossing -->\n")
    first = -0.5 * (ZEBRA_BARS - 1) * ZEBRA_PITCH
    for index in range(ZEBRA_BARS):
        parts.append(_box(
            f"zebra_{index}", (0.0, first + index * ZEBRA_PITCH, 0.0035),
            (ROAD_HALF_WIDTH - 0.02, ZEBRA_HALF_Y, 0.0035), "zebramat"))
    parts.append("\n        <!-- lane divider dashes -->\n")
    for index in range(-9, 10):
        if abs(index * 1.05) <= CROSSWALK_HALF_SPAN + 0.5:
            continue
        parts.append(_box(
            f"dash_{index + 9}", (0.0, index * 1.05, 0.0030),
            (0.022, 0.28, 0.0030), "dashmat"))
    parts.append("\n        <!-- wait lines and safe zone -->\n")
    for side, sx in (("near", -1.0), ("far", 1.0)):
        parts.append(_box(
            f"wait_line_{side}", (sx * WAIT_LINE_X, 0.0, 0.0045),
            (0.026, CROSSWALK_HALF_SPAN, 0.0045), "waitlinemat"))
    parts.append(_box("safe_zone", (SAFE_ZONE_X, 0.0, 0.0050),
                      (SAFE_ZONE_HALF, 0.50, 0.0050), "safezonemat"))
    return "".join(parts)


def furniture() -> str:
    """Sector poles, buildings and trees: depth cues, all non-colliding."""
    parts = ["\n        <!-- sector poles, buildings, trees -->\n"]
    for name, x, y, material in SECTOR_POLES:
        parts.append(
            f'        <body name="{name}" pos="{x:.3f} {y:.3f} 0">\n'
            f'            <geom name="{name}_shaft" type="cylinder"'
            f' pos="0 0 0.230" size="0.018 0.230" material="polemat"'
            f' contype="0" conaffinity="0" />\n'
            f'            <geom name="{name}_head" type="box" pos="0 0 0.480"'
            f' size="0.015 0.090 0.090" material="{material}"'
            f' contype="0" conaffinity="0" />\n'
            f"        </body>\n"
        )
    buildings = (
        (3.55, -2.60, 0.62, 0.85, 0.72), (3.75, 0.90, 0.70, 1.05, 0.95),
        (3.45, 4.20, 0.58, 1.15, 0.60), (-3.70, 1.60, 0.66, 1.30, 0.82),
        (-3.55, -3.40, 0.60, 0.95, 0.66),
    )
    for index, (x, y, sx, sy, h) in enumerate(buildings):
        parts.append(_box(f"building_{index}", (x, y, h), (sx, sy, h),
                          "buildingmat"))
        parts.append(_box(f"roof_{index}", (x, y, 2.0 * h + 0.03),
                          (sx + 0.04, sy + 0.04, 0.03), "roofmat"))
    trees = ((-1.95, 3.30), (1.95, -3.60), (2.05, 5.20), (-2.00, -5.00))
    for index, (x, y) in enumerate(trees):
        parts.append(
            f'        <geom name="tree_trunk_{index}" type="cylinder"'
            f' pos="{x:.2f} {y:.2f} 0.200" size="0.045 0.200"'
            f' material="trunkmat" contype="0" conaffinity="0" />\n'
            f'        <geom name="tree_crown_{index}" type="sphere"'
            f' pos="{x:.2f} {y:.2f} 0.480" size="0.230"'
            f' material="foliagemat" contype="0" conaffinity="0" />\n'
        )
    return "".join(parts)


def car_block(name: str, body_rgba: str, trim_rgba: str) -> str:
    """A small car: chassis, cabin, glass band, bumpers and four wheels."""
    lines = [
        f'        <body name="vehicle_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_chassis" type="box" pos="0 0 0.072"'
        f' size="0.215 0.100 0.046" material="{name}_body"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_cabin" type="box" pos="-0.010 0 0.146"'
        f' size="0.105 0.088 0.040" material="{name}_body"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_glass" type="box" pos="-0.010 0 0.152"'
        f' size="0.088 0.092 0.026" material="glassmat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_bumper_f" type="box" pos="0.213 0 0.052"'
        f' size="0.016 0.098 0.022" material="{name}_trim"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_bumper_r" type="box" pos="-0.213 0 0.052"'
        f' size="0.016 0.098 0.022" material="{name}_trim"'
        f' contype="0" conaffinity="0" />',
    ]
    for xi, xs in (("f", 0.140), ("r", -0.140)):
        for yi, ys in (("l", 0.101), ("r", -0.101)):
            lines.append(
                f'            <geom name="{name}_wheel_{xi}{yi}" type="cylinder"'
                f' pos="{xs:+.3f} {ys:+.3f} 0.042" size="0.042 0.017"'
                f' quat="0.7071068 0.7071068 0 0" material="tyremat"'
                f' contype="0" conaffinity="0" />'
            )
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def two_wheeler_block(name: str, body_rgba: str, trim_rgba: str) -> str:
    """A scooter/bicycle with a rider: two wheels, a frame and a torso."""
    lines = [
        f'        <body name="vehicle_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_wheel_f" type="cylinder"'
        f' pos="0.150 0 0.058" size="0.058 0.013"'
        f' quat="0.7071068 0.7071068 0 0" material="tyremat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_wheel_r" type="cylinder"'
        f' pos="-0.150 0 0.058" size="0.058 0.013"'
        f' quat="0.7071068 0.7071068 0 0" material="tyremat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_frame" type="box" pos="0 0 0.108"'
        f' size="0.150 0.026 0.020" material="{name}_body"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_column" type="capsule"'
        f' fromto="0.135 0 0.100 0.150 0 0.235" size="0.016"'
        f' material="{name}_trim" contype="0" conaffinity="0" />',
        f'            <geom name="{name}_bars" type="box" pos="0.148 0 0.240"'
        f' size="0.014 0.088 0.011" material="{name}_trim"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_rider" type="capsule"'
        f' fromto="-0.030 0 0.150 0.020 0 0.300" size="0.062"'
        f' material="ridermat" contype="0" conaffinity="0" />',
        f'            <geom name="{name}_rider_head" type="sphere"'
        f' pos="0.038 0 0.372" size="0.050" material="skinmat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_helmet" type="ellipsoid"'
        f' pos="0.038 0 0.392" size="0.055 0.055 0.040"'
        f' material="{name}_body" contype="0" conaffinity="0" />',
        "        </body>",
    ]
    return "\n".join(lines) + "\n"


def build() -> str:
    parts = [HEADER]
    materials = "".join(
        f'        <material name="{name}_body" rgba="{body}" />\n'
        f'        <material name="{name}_trim" rgba="{trim}" />\n'
        for name, _, body, trim in VEHICLES
    )
    parts[0] = HEADER.replace("    </asset>", materials + "    </asset>")
    parts.append(street())
    parts.append(furniture())
    parts.append("\n        <!-- road users: mocap, non-colliding, scripted -->\n")
    for name, kind, body, trim in VEHICLES:
        parts.append(
            car_block(name, body, trim) if kind == "car"
            else two_wheeler_block(name, body, trim))
    parts.append("    </worldbody>\n\n")
    # 7 free-joint qpos + 14 actuated joints.  Mocap bodies carry no qpos and
    # the street furniture is static, so there is nothing else to pad.
    stand = (
        "        -2.05 0 0.12 1 0 0 0\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * 14)
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="-2.05 0 0.12 1 0 0 0 {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = Path(__file__).resolve().parents[1] / "assets" / "scene_crosswalk_guardian.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
