#!/usr/bin/env python3
"""Emit assets/scene_move_away_crowd.xml.

Eight adult pedestrians around a child-sized Microduck, five of them carrying a
chest-height box that partly blocks their own downward view.  Every actor is a
MOCAP body with ``contype=0 conaffinity=0``: kinematic, non-colliding scenery.
They cannot push the robot, so an avoidance can never succeed because an actor
shoved the duck.  Markers for the selected threat, the predicted closest-approach
point and the evade goal are mocap discs, also non-colliding.

The scene is generated rather than hand-written so the eight bodies stay
consistent and the keyframe padding (4 hinges per adult) is computed, not
guessed.
"""

from __future__ import annotations

from pathlib import Path

# name, shirt rgba, carries a box (a box partly blocks the adult's own view)
ADULTS: tuple[tuple[str, str, bool], ...] = (
    ("blue", "0.10 0.32 0.92 1", False),
    ("green", "0.10 0.70 0.28 1", True),
    ("red", "0.88 0.12 0.14 1", True),
    ("yellow", "0.95 0.72 0.10 1", True),
    ("purple", "0.62 0.20 0.88 1", False),
    ("orange", "0.96 0.45 0.08 1", True),
    ("teal", "0.06 0.68 0.68 1", True),
    ("pink", "0.95 0.42 0.66 1", False),
)

MARKERS: tuple[tuple[str, str, str, str], ...] = (
    # name, size (radius half-height), material, z
    ("threat_marker", "0.085 0.004", "threatmat", "0.010"),
    ("predict_marker", "0.055 0.004", "predictmat", "0.011"),
    ("evade_marker", "0.045 0.004", "evademat", "0.012"),
)

HEADER = """<mujoco model="scene_move_away_crowd">
    <!-- move-away-crowd: eight adults, five carrying boxes, walking independent
         routes around a child-sized Microduck.  GENERATED by tools/build_scene.py
         - edit that script, not this file.

         Every adult and every marker is a mocap body with contype="0"
         conaffinity="0": kinematically scripted, never dynamically simulated,
         and physically unable to touch or push the robot.  They add no degrees
         of freedom to the floating base, so the walking policy sees exactly the
         robot it was trained on. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.62 0.62 0.62" ambient="0.32 0.32 0.32" specular="0 0 0" />
        <rgba haze="0.15 0.25 0.35 1" />
        <global azimuth="160" elevation="-20" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.30 0.50 0.70" rgb2="0 0 0"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.20 0.30 0.40" rgb2="0.10 0.20 0.30" markrgb="0.8 0.8 0.8"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="5 5" reflectance="0.2" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.08 0.12 0.22 1" />
        <material name="shoemat" rgba="0.04 0.04 0.05 1" />
        <material name="boxmat" rgba="0.76 0.56 0.32 1" />
        <material name="boxtapemat" rgba="0.90 0.86 0.74 1" />
        <material name="threatmat" rgba="1.0 0.30 0.25 0.80" />
        <material name="predictmat" rgba="1.0 0.85 0.20 0.75" />
        <material name="evademat" rgba="0.25 1.0 0.55 0.75" />
"""

FOOTER_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.6" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the attention camera used both for the
             PiP and for every visibility measurement, oriented with world up. -->
        <body name="attention_rig" mocap="true" pos="0 0 0.20">
            <camera name="attention_camera" fovy="58" />
        </body>
"""


def adult_block(name: str, rgba: str, box: bool, x: float, y: float) -> str:
    """One adult: torso, head, two hinged legs, two hinged arms, optional box."""
    shirt = f"{name}_shirt"
    lines = [
        f'        <body name="person_{name}" mocap="true" pos="{x:.2f} {y:.2f} 0.36">',
        f'            <geom name="{name}_torso" type="capsule" fromto="0 0 -0.10 0 0 0.16"'
        f' size="0.078" material="{shirt}" contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere" pos="0 0 0.255" size="0.064"'
        f' material="skinmat" contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere" pos="0.060 0 0.252" size="0.019"'
        f' material="{shirt}" contype="0" conaffinity="0" />',
    ]
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}" pos="0 {sy:+.3f} -0.10">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0" range="-40 40" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 -0.26" size="0.033"'
            f' material="trousermat" contype="0" conaffinity="0" />'
            f'<geom type="capsule" fromto="0 0 -0.26 0.072 0 -0.272" size="0.035"'
            f' material="shoemat" contype="0" conaffinity="0" /></body>'
        )
    if box:
        # Arms forward, hugging a box held at chest height.  The box sits in
        # front of the face and below eye level: this adult cannot see the
        # floor immediately ahead, which is exactly where a child-sized robot is.
        for side, sy in (("l", 0.078), ("r", -0.078)):
            lines.append(
                f'            <body name="{name}_arm_{side}" pos="0 {sy:+.3f} 0.115">'
                f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
                f' range="-30 30" damping="1" />'
                f'<geom type="capsule" fromto="0 0 0 0.150 {-0.020 if side == "l" else 0.020:+.3f} -0.055"'
                f' size="0.026" material="skinmat" contype="0" conaffinity="0" /></body>'
            )
        lines.append(
            f'            <geom name="{name}_box" type="box" pos="0.185 0 0.055"'
            f' size="0.115 0.140 0.105" material="boxmat" contype="0" conaffinity="0" />'
        )
        lines.append(
            f'            <geom name="{name}_box_tape" type="box" pos="0.185 0 0.161"'
            f' size="0.117 0.022 0.003" material="boxtapemat" contype="0" conaffinity="0" />'
        )
    else:
        for side, sy in (("l", 0.078), ("r", -0.078)):
            lines.append(
                f'            <body name="{name}_arm_{side}" pos="0 {sy:+.3f} 0.115">'
                f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
                f' range="-32 32" damping="1" />'
                f'<geom type="capsule" fromto="0 0 0 0 0 -0.205" size="0.026"'
                f' material="skinmat" contype="0" conaffinity="0" /></body>'
            )
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    parts = [HEADER]
    for name, rgba, _ in ADULTS:
        parts.append(f'        <material name="{name}_shirt" rgba="{rgba}" />\n')
    parts.append(FOOTER_OPEN)
    for name, _, _, in MARKERS[:0]:  # markers emitted below
        pass
    for mname, size, mat, z in MARKERS:
        parts.append(
            f'        <body name="{mname}" mocap="true" pos="0 0 {z}">\n'
            f'            <geom name="{mname}_disc" type="cylinder" size="{size}"'
            f' material="{mat}" contype="0" conaffinity="0" />\n'
            f"        </body>\n"
        )
    # Spread the initial poses; the routes in crowd_routes.py override them at t=0.
    ring = ((1.7, 0.2), (1.3, 1.1), (0.2, 1.6), (-1.2, 1.0),
            (-1.7, -0.2), (-1.1, -1.2), (0.3, -1.7), (1.4, -1.1))
    for (name, _, box), (x, y) in zip(ADULTS, ring):
        parts.append(adult_block(name, "", box, x, y))
    parts.append("    </worldbody>\n\n")

    # 7 free-joint qpos + 14 actuated joints + 4 hinges per adult.
    hinge_pad = " ".join(["0"] * (4 * len(ADULTS)))
    stand = (
        "        0 0 0.12 1 0 0 0\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 4 * len(ADULTS)))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="0 0 0.12 1 0 0 0 {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = Path(__file__).resolve().parents[1] / "assets" / "scene_move_away_crowd.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
