#!/usr/bin/env python3
"""Emit assets/scene_patrol.xml - an indoor facility with a hexagonal patrol
circuit, five marked checkpoints, a restricted zone and a populated floor.

GENERATED from ``scripts/patrol_facility.py`` and ``scripts/patrol_cast.py``
rather than hand-written, so the surfaces the clearance gate grades, the
fixtures the standoff planner prunes against, the bodies the choreography poses
and the geometry the camera ray-casts through are all the SAME objects.  Moving
a shelf moves it everywhere at once.

Everything except the robot is ``contype="0" conaffinity="0"``: kinematic
scenery that cannot touch or push the robot.  The bodies are mocap, posed
analytically each tick, so they add no degrees of freedom to the floating base
and the walking policy sees exactly the robot it was trained on.

THE FIXTURES BEING NON-COLLIDING IS DELIBERATE.  If they collided, "the duck
never walked into a shelf" would be enforced by the contact solver rather than
demonstrated by the controller.  With non-colliding scenery every claim is a
property of the SOFTWARE, graded by measured surface clearance every control
tick.

THE CHECKPOINTS AND THE RESTRICTED ZONE ARE PAINTED ON THE FLOOR, because both
are places the behavior makes claims about.  A viewer must be able to see the
duck stop ON a checkpoint and see that it never crossed into the marked
rectangle, rather than having to trust a HUD number.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from patrol_cast import (  # noqa: E402
    BODIES,
    OBJECT_HALF,
    OBJECT_HEIGHT_M,
    TROLLEY_WHEEL_DY,
    TROLLEY_WHEEL_R,
)
from patrol_facility import (  # noqa: E402
    CHECKPOINTS,
    DUCK_START_YAW_DEG,
    FIXTURES,
    FLOOR_HALF,
    HOME,
    HOME_PAD_HALF,
    RESTRICTED_ZONE,
    WALL_HALF_Z,
    WALL_T,
)

HEADER = """<mujoco model="scene_patrol">
    <!-- patrol-and-investigate: an indoor facility with a hexagonal patrol
         circuit round a central racking island, five painted checkpoints, a
         marked restricted zone, moving staff, and objects that appear during
         the run.
         GENERATED by tools/build_scene.py - edit that script, not this file.

         Every wall, shelf, column, bin, stanchion, checkpoint pad, zone marking,
         object and person is contype="0" conaffinity="0": kinematic scenery
         that cannot touch or push the robot.  Completing the patrol, stopping
         on each checkpoint, keeping a safe standoff and staying out of the
         restricted zone are therefore properties of the SOFTWARE, graded by
         measured surface clearance and by where the trunk actually went, not by
         the contact solver. -->
    <include file="robot_walk.xml" />

    <visual>
        <headlight diffuse="0.80 0.80 0.80" ambient="0.47 0.47 0.47" specular="0 0 0" />
        <rgba haze="0.17 0.19 0.24 1" />
        <global azimuth="150" elevation="-30" offwidth="1600" offheight="1200" />
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.16 0.18 0.24" rgb2="0.04 0.05 0.08"
                 width="512" height="3072" />
        <texture type="2d" name="groundplane" builtin="checker" mark="edge"
                 rgb1="0.27 0.27 0.30" rgb2="0.22 0.22 0.25" markrgb="0.37 0.37 0.41"
                 width="300" height="300" />
        <material name="groundplane" texture="groundplane" texuniform="true"
                  texrepeat="20 20" reflectance="0.05" />
        <material name="hallmat" rgba="0.44 0.44 0.42 1" />
        <material name="wallmat" rgba="0.68 0.67 0.64 1" />
        <material name="rackmat" rgba="0.44 0.40 0.36 1" />
        <material name="palletmat" rgba="0.42 0.34 0.22 1" />
        <material name="columnmat" rgba="0.58 0.58 0.60 1" />
        <material name="binmat" rgba="0.24 0.46 0.34 1" />
        <material name="postmat" rgba="0.94 0.74 0.16 1" />
        <material name="zonemat" rgba="0.96 0.36 0.30 0.30" />
        <material name="zonetapemat" rgba="0.98 0.42 0.22 0.85" />
        <material name="cpmat" rgba="0.30 0.72 0.96 0.34" />
        <material name="cpdonemat" rgba="0.30 0.94 0.60 0.42" />
        <material name="homemat" rgba="0.62 0.52 0.95 0.42" />
        <material name="loopmat" rgba="0.36 0.78 0.98 0.22" />
        <material name="objectmat" rgba="0.545 0.400 0.235 1" />
        <material name="trolleymat" rgba="0.620 0.640 0.680 1" />
        <material name="trolleywheelmat" rgba="0.14 0.14 0.16 1" />
        <material name="skinmat" rgba="0.86 0.66 0.52 1" />
        <material name="trousermat" rgba="0.12 0.15 0.22 1" />
        <material name="shoemat" rgba="0.05 0.05 0.06 1" />
        <material name="routemat" rgba="0.36 0.78 0.98 0.45" />
        <material name="memorymat" rgba="0.98 0.72 0.36 0.45" />
        <material name="standoffmat" rgba="0.98 0.36 0.42 0.34" />
        <material name="trailmat" rgba="0.62 0.52 0.95 0.32" />
        <material name="targetmat" rgba="0.98 0.24 0.30 0.55" />
"""

WORLD_OPEN = """    </asset>

    <worldbody>
        <light pos="0 0 3.8" dir="0 0 -1" directional="true" />
        <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"
              material="groundplane" />

        <!-- Rendering-only rig: carries the camera used both for the PiP and
             for every visibility measurement, oriented with world up. -->
        <body name="patrol_rig" mocap="true" pos="0 0 0.20">
            <camera name="patrol_camera" fovy="58" />
        </body>
"""

# How many world-space markers the scene carries.
ROUTE_DISCS = 22
TRAIL_DISCS = 18
MEMORY_DISCS = 10
STANDOFF_DISCS = 8


def _box(name, pos, size, material, quat=None) -> str:
    rotation = f' quat="{quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f} {quat[3]:.6f}"' \
        if quat else ""
    return (
        f'        <geom name="{name}" type="box" pos="{pos[0]:.4f} {pos[1]:.4f} '
        f'{pos[2]:.4f}" size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}"'
        f'{rotation} material="{material}" contype="0" conaffinity="0" />\n'
    )


def _cyl(name, pos, radius, half_h, material) -> str:
    return (
        f'        <geom name="{name}" type="cylinder" pos="{pos[0]:.4f} '
        f'{pos[1]:.4f} {pos[2]:.4f}" size="{radius:.4f} {half_h:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />\n'
    )


def hall() -> str:
    """Facility floor slab and the four perimeter walls."""
    parts = ["\n        <!-- facility floor and perimeter walls -->\n"]
    parts.append(_box("hall_floor", (0.0, 0.0, 0.0015),
                      (FLOOR_HALF[0], FLOOR_HALF[1], 0.0015), "hallmat"))
    for tag, sign in (("e", +1.0), ("w", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (sign * (FLOOR_HALF[0] + WALL_T), 0.0, WALL_HALF_Z),
            (WALL_T, FLOOR_HALF[1] + 2 * WALL_T, WALL_HALF_Z), "wallmat"))
    for tag, sign in (("n", +1.0), ("s", -1.0)):
        parts.append(_box(
            f"wall_{tag}", (0.0, sign * (FLOOR_HALF[1] + WALL_T), WALL_HALF_Z),
            (FLOOR_HALF[0] + 2 * WALL_T, WALL_T, WALL_HALF_Z), "wallmat"))
    return "".join(parts)


def fixtures() -> str:
    """Every static fixture in :data:`patrol_facility.FIXTURES`.

    Geom names come from the fixture's own name, so
    ``rollout_patrol.scenery_geom_names`` collects them from the model rather
    than from a hand-kept list and a new fixture cannot silently escape the
    clearance gate.
    """
    parts = ["\n        <!-- static racking, shelves, columns, stanchions -->\n"]
    for fixture in FIXTURES:
        half_h = 0.5 * fixture.height_m
        if fixture.kind == "cylinder":
            parts.append(_cyl(
                fixture.name,
                (fixture.center[0], fixture.center[1], half_h),
                fixture.radius, half_h, fixture.material))
        else:
            parts.append(_box(
                fixture.name,
                (fixture.center[0], fixture.center[1], half_h),
                (fixture.half[0], fixture.half[1], half_h),
                fixture.material))
    return "".join(parts)


def circuit_block() -> str:
    """The painted checkpoint pads, the home pad and the restricted zone.

    Real world geometry rather than HUD annotation, so a viewer can see the duck
    stop ON a checkpoint and see that it never crossed the marked rectangle.
    """
    parts = ["\n        <!-- the patrol circuit: painted pads and markings -->\n"]
    for index, checkpoint in enumerate(CHECKPOINTS):
        parts.append(_box(
            f"cp_pad_{index}", (checkpoint.xy[0], checkpoint.xy[1], 0.005),
            (0.19, 0.19, 0.005), "cpmat"))
    parts.append(_box("home_pad", (HOME.xy[0], HOME.xy[1], 0.006),
                      (HOME_PAD_HALF[0], HOME_PAD_HALF[1], 0.006), "homemat"))

    # The restricted zone: a painted rectangle plus tape along each edge, so it
    # reads as a marked-off area rather than a coloured patch.
    zone = RESTRICTED_ZONE
    parts.append(_box("zone_floor", (zone.center[0], zone.center[1], 0.004),
                      (zone.half[0], zone.half[1], 0.004), "zonemat"))
    for tag, dx, dy, hx, hy in (
            ("n", 0.0, +zone.half[1], zone.half[0], 0.022),
            ("s", 0.0, -zone.half[1], zone.half[0], 0.022),
            ("e", +zone.half[0], 0.0, 0.022, zone.half[1]),
            ("w", -zone.half[0], 0.0, 0.022, zone.half[1])):
        parts.append(_box(
            f"zone_tape_{tag}",
            (zone.center[0] + dx, zone.center[1] + dy, 0.008),
            (hx, hy, 0.008), "zonetapemat"))
    return "".join(parts)


def markers() -> str:
    """Mocap discs: the plan, the remembered route, the standoff, the target."""
    entries = [(f"route_{i}", "routemat", 0.030, 0.004)
               for i in range(ROUTE_DISCS)]
    entries += [(f"trail_{i}", "trailmat", 0.032, 0.004)
                for i in range(TRAIL_DISCS)]
    entries += [(f"memory_{i}", "memorymat", 0.038, 0.005)
                for i in range(MEMORY_DISCS)]
    entries += [(f"standoff_{i}", "standoffmat", 0.040, 0.005)
                for i in range(STANDOFF_DISCS)]
    entries += [("target_marker", "targetmat", 0.100, 0.006)]
    entries += [("checkpoint_marker", "cpdonemat", 0.120, 0.007)]
    parts = ["\n        <!-- route, memory, standoff and target markers -->\n"]
    for name, material, radius, half_h in entries:
        parts.append(
            f'        <body name="{name}" mocap="true" pos="0 0 -3.0">\n'
            f'            <geom name="{name}_disc" type="cylinder"'
            f' size="{radius:.3f} {half_h:.3f}" material="{material}"'
            f' contype="0" conaffinity="0" />\n'
            f"        </body>\n")
    return "".join(parts)


def person_block(body) -> str:
    """One person, SCALED BY STATURE, with swinging limbs."""
    s = body.stature
    name = body.name
    lines = [
        f'        <body name="actor_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_torso" type="capsule"'
        f' fromto="0 0 {-0.10 * s:.4f} 0 0 {0.16 * s:.4f}"'
        f' size="{0.078 * s:.4f}" material="{name}_shirt"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_head" type="sphere"'
        f' pos="0 0 {0.255 * s:.4f}" size="{0.064 * s:.4f}" material="skinmat"'
        f' contype="0" conaffinity="0" />',
        f'            <geom name="{name}_face" type="sphere"'
        f' pos="{0.060 * s:.4f} 0 {0.252 * s:.4f}" size="{0.019 * s:.4f}"'
        f' material="{name}_shirt" contype="0" conaffinity="0" />',
    ]
    for side, sy in (("l", 0.036), ("r", -0.036)):
        lines.append(
            f'            <body name="{name}_leg_{side}"'
            f' pos="0 {sy * s:+.4f} {-0.10 * s:.4f}">'
            f'<joint name="{name}_hip_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.26 * s:.4f}"'
            f' size="{0.033 * s:.4f}" material="trousermat"'
            f' contype="0" conaffinity="0" />'
            f'<geom type="capsule"'
            f' fromto="0 0 {-0.26 * s:.4f} {0.072 * s:.4f} 0 {-0.272 * s:.4f}"'
            f' size="{0.035 * s:.4f}" material="shoemat"'
            f' contype="0" conaffinity="0" /></body>')
    for side, sy in (("l", 0.078), ("r", -0.078)):
        lines.append(
            f'            <body name="{name}_arm_{side}"'
            f' pos="0 {sy * s:+.4f} {0.115 * s:.4f}">'
            f'<joint name="{name}_shoulder_{side}" type="hinge" axis="0 1 0"'
            f' range="-42 42" damping="1" />'
            f'<geom type="capsule" fromto="0 0 0 0 0 {-0.205 * s:.4f}"'
            f' size="{0.026 * s:.4f}" material="skinmat"'
            f' contype="0" conaffinity="0" /></body>')
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def object_block(body) -> str:
    """One object: a real box with real extents the clearance probe measures.

    The mocap origin sits on the FLOOR, so the geoms are built upward from
    ``z = 0`` and the body's own sample heights in ``patrol_cast`` describe the
    same solid the camera ray-casts against.
    """
    name = body.name
    half = OBJECT_HALF[body.kind]
    height = OBJECT_HEIGHT_M[body.kind]
    material = "objectmat" if body.kind == "object" else "trolleymat"
    lines = [
        f'        <body name="actor_{name}" mocap="true" pos="0 0 -3.0">',
        f'            <geom name="{name}_body" type="box"'
        f' pos="0 0 {0.5 * height:.4f}"'
        f' size="{half[0]:.4f} {half[1]:.4f} {0.5 * height:.4f}"'
        f' material="{material}" contype="0" conaffinity="0" />',
    ]
    if body.kind == "object":
        # A banding strap, so a crate reads as a crate in the PiP.
        lines.append(
            f'            <geom name="{name}_strap" type="box"'
            f' pos="0 0 {0.62 * height:.4f}"'
            f' size="{half[0] + 0.004:.4f} {0.018:.4f} {0.016:.4f}"'
            f' material="{name}_shirt" contype="0" conaffinity="0" />')
    else:
        # A handle and two wheels, so a trolley reads as a trolley.
        lines.append(
            f'            <geom name="{name}_handle" type="capsule"'
            f' fromto="{-half[0]:.4f} {-0.10:.4f} {height + 0.10:.4f}'
            f' {-half[0]:.4f} {0.10:.4f} {height + 0.10:.4f}" size="0.014"'
            f' material="trolleywheelmat" contype="0" conaffinity="0" />')
        lines.append(
            f'            <geom name="{name}_post" type="capsule"'
            f' fromto="{-half[0]:.4f} 0 {height:.4f}'
            f' {-half[0]:.4f} 0 {height + 0.10:.4f}" size="0.012"'
            f' material="trolleywheelmat" contype="0" conaffinity="0" />')
        for tag, sy in (("l", +TROLLEY_WHEEL_DY), ("r", -TROLLEY_WHEEL_DY)):
            lines.append(
                f'            <geom name="{name}_wheel_{tag}" type="sphere"'
                f' pos="{half[0] - 0.03:.4f} {sy:+.4f} {TROLLEY_WHEEL_R:.4f}"'
                f' size="{TROLLEY_WHEEL_R:.4f}" material="trolleywheelmat"'
                f' contype="0" conaffinity="0" />')
    lines.append("        </body>")
    return "\n".join(lines) + "\n"


def build() -> str:
    materials = "".join(
        f'        <material name="{b.name}_shirt" rgba="{b.rgba}" />\n'
        for b in BODIES)
    parts = [HEADER + materials + WORLD_OPEN,
             hall(), fixtures(), circuit_block(), markers(),
             "\n        <!-- the population: mocap, non-colliding -->\n"]
    for body in BODIES:
        parts.append(person_block(body) if body.is_person
                     else object_block(body))
    parts.append("    </worldbody>\n\n")

    yaw = math.radians(DUCK_START_YAW_DEG)
    quat = (math.cos(0.5 * yaw), 0.0, 0.0, math.sin(0.5 * yaw))
    base = (f"{HOME.xy[0]:.4f} {HOME.xy[1]:.4f} 0.12 "
            f"{quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f} {quat[3]:.6f}")
    people = sum(1 for b in BODIES if b.is_person)
    hinge_pad = " ".join(["0"] * (4 * people))
    stand = (
        f"        {base}\n"
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984\n"
        f"        {hinge_pad}"
    )
    ctrl = (
        "        0 -0.08726646259971647 -0.457924 -0.004940 0.452984\n"
        "        0.3490658503988659 0.3490658503988659 0 0\n"
        "        0 0.08726646259971647 0.457924 0.004940 -0.452984"
    )
    init_pad = " ".join(["0"] * (14 + 4 * people))
    parts.append(
        "    <keyframe>\n"
        f'        <key name="INIT" qpos="{base} {init_pad}"\n'
        '             ctrl="0 0 0 0 0 0 0 0 0 0 0 0 0 0" />\n'
        f'        <key name="STAND" qpos="\n{stand}"\n'
        f'             ctrl="\n{ctrl}" />\n'
        "    </keyframe>\n</mujoco>\n"
    )
    return "".join(parts)


def main() -> int:
    out = (Path(__file__).resolve().parents[1] / "assets" / "scene_patrol.xml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    print(f"  bodies={len(BODIES)}  fixtures={len(FIXTURES)}  "
          f"checkpoints={len(CHECKPOINTS)}  home={HOME.xy}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
